export const ALL_QUESTIONS = [
  { id:1, topic:"Syntax Errors",
    question:"Which of the following would cause a syntax error?",
    code:`# Which line has a syntax error?\nA: print("Hello")\nB: x = 5 + 3\nC: if x = 5:\nD: y = int("10")`,
    options:['print("Hello")', "x = 5 + 3", "if x = 5:", 'y = int("10")'],
    correct:2,
    hint:"Think about what = does in Python vs ==",
    explanation:'if x = 5: is a syntax error because = is assignment, not comparison. Use == to compare.',
    defaultRunnable:`x = 5\nif x == 5:\n    print("Correct operator!")\n# if x = 5:  ← SyntaxError`,
  },
  { id:2, topic:"Pseudocode & Algorithms",
    question:"What best describes pseudocode?",
    code:`# PSEUDOCODE (planning):\n# GET user's age\n# IF age >= 18 THEN\n#     PRINT "Adult"\n# ELSE\n#     PRINT "Minor"\n\n# REAL PYTHON:\nage = 20\nif age >= 18:\n    print("Adult")`,
    options:["A programming language used before Python","Informal steps describing an algorithm in plain language","Python code with lots of comments","A type of flowchart diagram"],
    correct:1,
    hint:'The word "pseudo" means fake or informal',
    explanation:"Pseudocode is informal, readable language used to plan an algorithm before writing real code. No strict syntax — the goal is clarity of logic.",
    defaultRunnable:`# Pseudocode → Python:\n# GET two numbers, PRINT the larger\na, b = 8, 3\nif a > b: print(a, "is larger")\nelif b > a: print(b, "is larger")\nelse: print("Equal")`,
  },
  { id:3, topic:"Escape Characters",
    question:'What does print("Line1\\nLine2\\tEnd") output?',
    code:`print("Line1\\nLine2\\tEnd")`,
    options:['Prints literally: Line1\\nLine2\\tEnd',"Line1, newline, Line2, tab, then End","Line1Line2End on one line","SyntaxError"],
    correct:1,
    hint:"The backslash \\ creates special invisible characters",
    explanation:"\\n is a newline and \\t is a tab. These escape sequences represent characters that can't be typed directly.",
    defaultRunnable:`print("Line1\\nLine2\\tEnd")\nprint("She said \\"hello\\"")\nprint("A\\nB\\nC")\nprint("Col1\\tCol2\\tCol3")`,
  },
  { id:4, topic:"print() end Argument",
    question:"What is the output?",
    code:`print("Hello", end=" ")\nprint("World", end="!")\nprint()`,
    options:["Hello\\nWorld!\\n","Hello World!","Hello\\nWorld!","HelloWorld!"],
    correct:1,
    hint:"The end parameter replaces the default newline at the end of print()",
    explanation:'By default print() ends with \\n. end=" " replaces that with a space. The final print() just outputs a newline.',
    defaultRunnable:`print("Hello", end=" ")\nprint("World", end="!")\nprint()\nfor i in range(5):\n    print(i, end=", ")`,
  },
  { id:5, topic:"int() Function",
    question:"What does int(3.99) return?",
    code:`print(int(3.99))\nprint(int(-3.9))\nprint(int("42"))`,
    options:["4 (rounds up)","3 (truncates toward zero)","-4","Error"],
    correct:1,
    hint:"int() chops the decimal off — it does NOT round",
    explanation:"int() truncates toward zero. int(3.99)→3. int(-3.9)→-3 (not -4). Use round() for rounding.",
    defaultRunnable:`print(int(3.99))   # 3\nprint(int(-3.9))  # -3\nprint(round(3.99)) # 4\nprint(int("42"))   # 42`,
  },
  { id:6, topic:"Math Expressions",
    question:"What is the result of this expression?",
    code:`result = 10 + 2 ** 3 * 2 - 6 / 3\nprint(result)`,
    options:["24.0","22.0","18.0","20.0"],
    correct:0,
    hint:"Use PEMDAS: ** first, then * and /, then + and -",
    explanation:"2**3=8, 8*2=16, 6/3=2.0, 10+16=26, 26-2.0=24.0. Division always returns a float.",
    fillBlankAnswer:"24.0",
    defaultRunnable:`result = 10 + 2 ** 3 * 2 - 6 / 3\nprint(result)\nstep1 = 2 ** 3\nstep2 = step1 * 2\nstep3 = 6 / 3\nstep4 = 10 + step2 - step3\nprint(step4)`,
  },
  { id:7, topic:"User Input",
    question:"A user types 98.6. Which line correctly stores it as a number?",
    code:`# User types: 98.6\nA: x = input("Temp: ")\nB: x = int(input("Temp: "))\nC: x = float(input("Temp: "))\nD: x = str(input("Temp: "))`,
    options:['input() — stores as string "98.6"',"int(input()) — crashes on 98.6","float(input()) — stores as 98.6 ✓","str(input()) — same as no conversion"],
    correct:2,
    hint:"input() always returns a string, no matter what the user types",
    explanation:"input() always returns a string. float() converts it to a float. int() would crash on '98.6'.",
    defaultRunnable:`raw = "98.6"\nprint(type(raw), raw)\nprint(type(float(raw)), float(raw))\nprint(type(int(float(raw))), int(float(raw)))`,
  },
  { id:8, topic:"Formatting Floats",
    question:"What does this f-string print?",
    code:`pi = 3.14159\nprint(f"Pi is {pi:.2f} and {pi:.4f}")`,
    options:["Pi is 3.14159 and 3.14159","Pi is 3.14 and 3.1416","Pi is 3 and 3.14","SyntaxError — invalid format"],
    correct:1,
    hint:":.2f means: format as float with 2 decimal places",
    explanation:":.2f formats with 2 decimal places. :.4f uses 4 — and rounds: 3.14159 → 3.1416.",
    defaultRunnable:`pi = 3.14159265\nprint(f"2dp: {pi:.2f}")\nprint(f"4dp: {pi:.4f}")\nprice = 4.5\nprint(f"Price: \${price:.2f}")\nbig = 1234567.89\nprint(f"Big: {big:,.2f}")`,
  },
  { id:9, topic:"Boolean Type",
    question:"Which of these is an actual bool type?",
    code:`a = True\nb = 0\nc = "False"\nd = 5 > 3`,
    options:["0 — it is falsy",'"False" — it contains False',"True and (5 > 3) — both are bool","All of the above"],
    correct:2,
    hint:"The bool type has exactly two values: True and False",
    explanation:"True is bool, 5>3 evaluates to True (also bool). 0 is int. \"False\" is str.",
    defaultRunnable:`print(type(True))    # bool\nprint(type(5 > 3))   # bool\nprint(type(0))       # int\nprint(type("False")) # str\nprint(bool(0), bool(""), bool(42), bool("hi"))`,
  },
  { id:10, topic:"Logical Operators",
    question:"What does this code print?",
    code:`x = 7\nprint(x > 5 and x < 10)\nprint(x < 0 or x > 5)\nprint(not x == 7)`,
    options:["True\nTrue\nTrue","True\nTrue\nFalse","False\nTrue\nFalse","True\nFalse\nFalse"],
    correct:1,
    hint:"Evaluate each part: x>5? x<10? Then apply and/or/not",
    explanation:"(x>5 and x<10)=True. (x<0 or x>5)=True. (not x==7)=not True=False.",
    defaultRunnable:`x = 7\nprint(x > 5 and x < 10)\nprint(x < 0 or x > 5)\nprint(not x == 7)\nfor a,b in [(True,True),(True,False),(False,False)]:\n    print(f"  {a} and {b} = {a and b}")`,
  },
  { id:11, topic:"Short-Circuit Evaluation",
    question:"What happens here when x = 0?",
    code:`x = 0\nresult = x != 0 and (10 / x > 2)\nprint(result)`,
    options:["ZeroDivisionError crash","False — right side is skipped entirely","True","None"],
    correct:1,
    hint:"With 'and', if the LEFT side is False, Python never checks the right side",
    explanation:"Short-circuit: x!=0 is False, so 10/x never runs. No crash!",
    defaultRunnable:`x = 0\nresult = x != 0 and (10 / x > 2)\nprint("and short-circuit:", result)\ny = 5\nresult2 = y == 5 or (1 / 0 > 0)\nprint("or short-circuit:", result2)`,
  },
  { id:12, topic:"if Statements",
    question:"What is printed?",
    code:`score = 85\nif score >= 90:\n    print("A")\nelif score >= 80:\n    print("B")\nelif score >= 70:\n    print("C")\nelse:\n    print("F")`,
    options:["A","B","C","B and C both print"],
    correct:1,
    hint:"Python checks top-to-bottom and runs the FIRST matching branch only",
    explanation:"score=85 fails >=90, passes >=80, so 'B' prints. All other branches are skipped.",
    defaultRunnable:`for s in [92, 85, 74, 55]:\n    if s>=90: g="A"\n    elif s>=80: g="B"\n    elif s>=70: g="C"\n    else: g="F"\n    print(f"{s} → {g}")`,
  },
  { id:13, topic:"if-else & Indentation",
    question:"What is printed when x = 3?",
    code:`x = 3\nif x > 5:\n    print("big")\n    print("number")\nprint("done")`,
    options:["big\nnumber\ndone","done","big\ndone","Nothing at all"],
    correct:1,
    hint:"Only the indented lines belong to the if block",
    explanation:'x=3 is not >5, so the indented block is skipped. print("done") is NOT indented, so it always runs.',
    defaultRunnable:`x = 3\nif x > 5:\n    print("big")\n    print("number")\nprint("done")\n# Try x = 10 to see both branches`,
  },
  { id:14, topic:"Condition vs Count-Controlled",
    question:"Which correctly distinguishes for vs while loops?",
    code:`# Count-controlled:\nfor i in range(5):\n    print(i)\n\n# Condition-controlled:\nx = 0\nwhile x < 5:\n    print(x)\n    x += 1`,
    options:["for loops are always faster","for loops run a known number of times; while runs until a condition is False","while loops are count-controlled; for is condition-controlled","They always produce identical results"],
    correct:1,
    hint:"for = you know the count in advance; while = you don't",
    explanation:"A for loop iterates a fixed number of times. A while loop runs until its condition is False.",
    defaultRunnable:`import random\nprint("FOR — count-controlled:")\nfor i in range(5): print(i, end=" ")\nprint("\nWHILE — condition-controlled:")\nc=0\nwhile random.randint(1,6)!=6: c+=1\nprint(f"Rolled {c} times before a 6")`,
  },
  { id:15, topic:"range() Function",
    question:"What does range(0, 9, 3) produce?",
    code:`for n in range(0, 9, 3):\n    print(n, end=" ")`,
    options:["0 3 6 9","0 3 6","3 6 9","0 3 6 9 12"],
    correct:1,
    hint:"range(start, stop, step) — the stop value is never included",
    explanation:"Starts at 0, steps by 3, stops BEFORE 9. Values: 0, 3, 6.",
    defaultRunnable:`for n in range(0,9,3): print(n,end=" ")\nprint()\nfor n in range(10,0,-1): print(n,end=" ")\nprint()\nfor n in range(5): print(n,end=" ")`,
  },
  { id:16, topic:"Augmented Assignment",
    question:"What is x after this code?",
    code:`x = 10\nx += 5\nx *= 2\nx -= 8\nprint(x)`,
    options:["16","22","24","30"],
    correct:1,
    hint:"Trace through: start at 10, apply each operator in order",
    explanation:"x=10 → +=5 → 15 → *=2 → 30 → -=8 → 22.",
    fillBlankAnswer:"22",
    defaultRunnable:`x = 10\nprint(f"Start:  {x}")\nx += 5;  print(f"+= 5:   {x}")\nx *= 2;  print(f"*= 2:   {x}")\nx -= 8;  print(f"-= 8:   {x}")`,
  },
  { id:17, topic:"Accumulator Pattern",
    question:"What does this loop print at the end?",
    code:`total = 0\nfor i in range(1, 6):\n    total += i\nprint(total)`,
    options:["5","14","15","6"],
    correct:2,
    hint:"Add each number: 0 + 1 + 2 + 3 + 4 + 5 = ?",
    explanation:"An accumulator starts at 0 and collects a running sum. 1+2+3+4+5 = 15.",
    fillBlankAnswer:"15",
    defaultRunnable:`total = 0\nfor i in range(1,6):\n    total += i\n    print(f"  +{i} → total={total}")\nprint(f"Final: {total}")`,
  },
  { id:18, topic:"Input Validation",
    question:"What is the purpose of input validation?",
    code:`grade = int(input("Enter grade (0-100): "))\nwhile grade < 0 or grade > 100:\n    print("Invalid!")\n    grade = int(input("Enter grade (0-100): "))\nprint("Accepted:", grade)`,
    options:["To format numbers to 2 decimal places","To check if the user typed fast enough","To keep asking until the user provides valid data","To convert strings to integers automatically"],
    correct:2,
    hint:"The loop keeps running while the condition is True — i.e., while the input is bad",
    explanation:"Input validation uses a loop to reject bad input and keep asking until valid data is provided.",
    defaultRunnable:`def get_valid(val):\n    grade = val\n    while grade < 0 or grade > 100:\n        print(f"  {grade} is invalid...")\n        grade += 50\n    return grade\nprint("Accepted:", get_valid(-10))`,
  },
  { id:19, topic:"while Loops",
    question:"How many times does the loop body execute?",
    code:`n = 1\nwhile n < 100:\n    n *= 3\nprint(n)`,
    options:["4 times, prints 81","5 times, prints 243","3 times, prints 27","Infinite loop"],
    correct:1,
    hint:"Trace through: 1 → 3 → 9 → 27 → 81 → 243. When does n ≥ 100?",
    explanation:"n: 1→3→9→27→81→243. After n=81, 81<100 so body runs again making n=243. 5 times total.",
    fillBlankAnswer:"243",
    defaultRunnable:`n=1; count=0\nwhile n<100:\n    n*=3; count+=1\n    print(f"  Iteration {count}: n={n}")\nprint(f"Ran {count} times, n={n}")`,
  },
  { id:20, topic:"Lists",
    question:"What is printed?",
    code:`items = ["a", "b", "c", "d"]\nitems[2] = "Z"\nprint(items[-1], items[2])`,
    options:["Z d","d Z","c Z","Z c"],
    correct:1,
    hint:"items[-1] is the last element. Count from the end.",
    explanation:'items[2] changes to "Z". items[-1] is the last element = "d" (unchanged). Prints: d Z.',
    defaultRunnable:`items = ["a","b","c","d"]\nitems[2] = "Z"\nprint(items[-1], items[2])\nitems.append("e")\nprint("After append:", items)\nprint("Length:", len(items))`,
  },
  { id:21, topic:"for Loops & Lists",
    question:"What is printed?",
    code:`nums = [2, 4, 6, 8]\ntotal = 0\nfor n in nums:\n    total += n\nprint(total)`,
    options:["8","20","4","2468"],
    correct:1,
    hint:"Add each element: 2 + 4 + 6 + 8 = ?",
    explanation:"The for loop iterates through each item, accumulating the total. 2+4+6+8 = 20.",
    defaultRunnable:`nums = [2,4,6,8]\ntotal = 0\nfor n in nums:\n    total += n\n    print(f"  +{n} → total={total}")\nprint(f"Sum: {total}")\nprint("Built-in:", sum(nums))`,
  },
  { id:22, topic:"void vs value-returning",
    question:"What is the key difference?",
    code:`def show(name):\n    print("Hi, " + name)\n\ndef make(name):\n    return "Hi, " + name\n\nx = show("Lee")\ny = make("Lee")`,
    options:["No difference — same result","show() prints (void, returns None); make() returns a value","make() is invalid without print()","show() is slower"],
    correct:1,
    hint:"Void functions perform an action but return None",
    explanation:"Void functions print/act and return None. Value-returning functions use return. x=show()→None. y=make()→the string.",
    defaultRunnable:`def show(name):\n    print("Hi, " + name)\ndef make(name):\n    return "Hi, " + name\nx = show("Lee")\nprint("x =", x)\ny = make("Lee")\nprint("y =", y)`,
  },
  { id:23, topic:"Functions — Define & Call",
    question:"What is printed?",
    code:`def double(n):\n    return n * 2\n\ndef add_one(n):\n    return n + 1\n\nprint(add_one(double(3)))`,
    options:["7","8","6","Error"],
    correct:0,
    hint:"Evaluate the innermost call first: what does double(3) return?",
    explanation:"double(3)=6, then add_one(6)=7.",
    fillBlankAnswer:"7",
    defaultRunnable:`def double(n): return n*2\ndef add_one(n): return n+1\nprint(add_one(double(3)))\nprint(add_one(add_one(double(5))))`,
  },
  { id:24, topic:"Local vs Global Variables",
    question:"What is printed?",
    code:`count = 0\n\ndef increment():\n    count = 10\n    print("inside:", count)\n\nincrement()\nprint("outside:", count)`,
    options:["inside: 10\noutside: 10","inside: 10\noutside: 0","inside: 0\noutside: 0","NameError"],
    correct:1,
    hint:"count = 10 inside the function creates a separate local variable",
    explanation:"Inside increment(), count=10 creates a LOCAL variable. The global count (0) is unaffected.",
    defaultRunnable:`count = 0\ndef increment():\n    count = 10\n    print("inside:", count)\ndef really_increment():\n    global count\n    count += 1\nincrement()\nprint("after increment():", count)\nreally_increment()\nprint("after really_increment():", count)`,
  },
  { id:25, topic:"Walrus Operator",
    question:"What does the walrus operator (:=) do?",
    code:`import random\n\n# Without walrus — repetitive:\nn = random.randint(1, 10)\nwhile n != 7:\n    n = random.randint(1, 10)\n\n# With walrus — concise:\nwhile (n := random.randint(1, 10)) != 7:\n    print(n)`,
    options:["Compares values like ==","Assigns a value AND returns it in one expression","Creates a deep copy","Divides and assigns like /="],
    correct:1,
    hint:":= assigns AND returns a value in the same expression",
    explanation:"The walrus operator := assigns a value AND returns it. Most useful in while loops to avoid writing the same call twice.",
    defaultRunnable:`import random\nrandom.seed(42)\nprint("Rolling until >= 8:")\nwhile (roll := random.randint(1,10)) < 8:\n    print(f"  Got {roll}...")\nprint(f"  Got {roll} — done!")`,
  },

  // ── Ch. 6 — Lists Deep Dive ───────────────────────────────────────────────

  { id:26, topic:"List Indexing",
    question:"What is printed?",
    code:`animals = ["cat", "dog", "bird", "fish"]\nprint(animals[0])\nprint(animals[-2])\nprint(animals[3])`,
    options:["cat, dog, fish","cat, bird, fish","dog, bird, bird","cat, bird, bird"],
    correct:1,
    hint:'Positive indexes count from the front (0 = first element). Negative indexes count from the back: -1 = last, -2 = second-to-last. The list has 4 items — which item is at -2?',
    explanation:'animals[0] is the first element → "cat". animals[-2] counts 2 from the end: the list is ["cat","dog","bird","fish"], so 2nd from the end is "bird". animals[3] is index 3 (the 4th element) → "fish". Three separate print() calls produce three lines of output: cat / bird / fish.',
    defaultRunnable:`animals = ["cat", "dog", "bird", "fish"]\nprint(animals[0])   # first\nprint(animals[-2])  # second-to-last\nprint(animals[3])   # last`,
  },
  { id:27, topic:"Lists vs Tuples",
    question:"What is the key difference between a list and a tuple?",
    code:`my_list  = [1, 2, 3]   # mutable\nmy_tuple = (1, 2, 3)   # immutable\n\nmy_list[0] = 99   # works fine\nmy_tuple[0] = 99  # TypeError!`,
    options:["Tuples can only hold numbers; lists hold anything","Lists are mutable (changeable); tuples are immutable (fixed)","Tuples are faster but otherwise identical","Lists use [] and tuples use () — that's the only difference"],
    correct:1,
    hint:"Try running my_tuple[0] = 99 — what happens? The key difference is not bracket style or content type, but whether you can change the contents after creation.",
    explanation:"Lists are mutable — you can change, add, or remove elements after creation. Tuples are immutable — once created, the contents cannot be modified; any attempt raises TypeError. Both can hold mixed types. Use tuples for fixed data (like coordinates) and lists for data that changes over time.",
    defaultRunnable:`my_list  = [1, 2, 3]\nmy_tuple = (1, 2, 3)\nmy_list[0] = 99\nprint("List:", my_list)\nprint("Tuple:", my_tuple)\n# my_tuple[0] = 99  # would raise TypeError`,
  },
  { id:28, topic:"range() to list",
    question:"How do you convert range(1, 6) into an actual list?",
    code:`# Which correctly produces [1, 2, 3, 4, 5]?\nA: range(1, 6)\nB: list(range(1, 6))\nC: [range(1, 6)]\nD: range.list(1, 6)`,
    options:["range(1, 6) — already a list","list(range(1, 6)) — wraps range in list()","[range(1, 6)] — bracket syntax","range.list(1, 6) — built-in method"],
    correct:1,
    hint:"range() returns a lazy range object that generates numbers on demand — it is NOT a list. Python's built-in list() function converts any iterable into a proper list. Think: list(...).",
    explanation:"range() returns a range object, not a list. To convert: list(range(1, 6)) → [1, 2, 3, 4, 5]. Option A fails because range alone is still a range object. Option C puts the range object inside a list as a single item: [range(0, 6)] — not the same thing. Option D doesn't exist in Python.",
    defaultRunnable:`r = range(1, 6)\nprint(type(r), r)\nresult = list(r)\nprint(type(result), result)\nprint(list(range(0, 10, 2)))`,
  },
  { id:29, topic:"List/Tuple Conversion",
    question:"What does this code print?",
    code:`data = (10, 20, 30)\nas_list = list(data)\nas_list.append(40)\nback = tuple(as_list)\nprint(back)`,
    options:["(10, 20, 30)","[10, 20, 30, 40]","(10, 20, 30, 40)","TypeError"],
    correct:2,
    hint:"Trace each step: list() converts the tuple to a mutable list so you can append. Then tuple() converts back. What does the final tuple look like, and which brackets does Python use when printing a tuple?",
    explanation:"Step by step: data = (10, 20, 30). list(data) → [10, 20, 30] (now a mutable list). .append(40) → [10, 20, 30, 40]. tuple([10, 20, 30, 40]) → (10, 20, 30, 40). Python prints tuples with round brackets (). Option B shows square brackets — that would be a list, not a tuple.",
    defaultRunnable:`data = (10, 20, 30)\nas_list = list(data)\nas_list.append(40)\nback = tuple(as_list)\nprint(back)\nprint(type(back))`,
  },
  { id:30, topic:"List Repetition",
    question:"What does the * operator do with lists?",
    code:`a = [0] * 4\nb = [1, 2] * 3\nprint(a)\nprint(b)`,
    options:["Error — * only works with numbers","[0, 0, 0, 0] and [1, 2, 1, 2, 1, 2]","[0, 4] and [1, 2, 3]","[[0]*4] and [[1,2]*3]"],
    correct:1,
    hint:"[0] * 4 repeats the list [0] four times end-to-end — it is NOT multiplying the number 0 by 4. [1, 2] * 3 repeats the whole two-element list three times.",
    explanation:"The * operator repeats list contents n times: [0] * 4 → [0, 0, 0, 0] (the list [0] repeated 4 times, giving 4 elements). [1, 2] * 3 → [1, 2, 1, 2, 1, 2] (the list [1, 2] repeated 3 times, giving 6 elements). This is identical to string repetition: 'ab' * 3 → 'ababab'.",
    defaultRunnable:`a = [0] * 4\nb = [1, 2] * 3\nprint(a)\nprint(b)\nprint([None] * 5)`,
  },
  { id:31, topic:"List Exceptions",
    question:"Which exception is raised by this code?",
    code:`items = ["a", "b", "c"]\nprint(items[5])`,
    options:["ValueError","KeyError","IndexError","TypeError"],
    correct:2,
    hint:'The list has 3 elements with valid indices 0, 1, 2 (and negatives -1, -2, -3). Index 5 is way past the end. Python raises a specific error for out-of-range indexes — not ValueError (wrong value) or TypeError (wrong type).',
    explanation:'items has 3 elements, so valid indices are 0, 1, 2. Accessing index 5 is outside this range → IndexError: list index out of range. Cheat sheet: IndexError = bad index; ValueError = value not found (e.g., .remove("z") when "z" isn\'t in the list); TypeError = wrong type used as index (e.g., items[1.5]); KeyError = missing key in a dictionary.',
    defaultRunnable:`items = ["a", "b", "c"]\ntry:\n    print(items[5])\nexcept IndexError as e:\n    print("IndexError:", e)\ntry:\n    items.remove("z")\nexcept ValueError as e:\n    print("ValueError:", e)`,
  },
  { id:32, topic:"len() Function",
    question:"What is printed?",
    code:`words = ["hello", "world", "python"]\nprint(len(words))\nprint(len(words[0]))`,
    options:["Prints 3, then 5","Prints 5, then 3","Prints 3, then 3","Prints 2, then 5"],
    correct:0,
    hint:'There are two separate print() calls — each produces one line of output, in the order they appear in the code. The FIRST print calls len() on the whole list (how many words = 3?). The SECOND calls len() on words[0] = "hello" (how many characters = 5?). So the output is 3 on line 1, then 5 on line 2.',
    explanation:'The two print() calls run top-to-bottom. First: len(words) = len(["hello", "world", "python"]) = 3 (three items in the list). Second: len(words[0]) = len("hello") = 5 (five characters). Output is 3 on the first line, 5 on the second → "Prints 3, then 5". Common mistake: choosing "Prints 5, then 3" by thinking of the string length first — but the LIST length is printed first because that print() line comes first.',
    defaultRunnable:`words = ["hello", "world", "python"]\nprint(len(words))      # 3 elements in the list\nprint(len(words[0]))   # 5 chars in "hello"\nprint(len([]))         # 0`,
  },
  { id:33, topic:"for Loops & Strings",
    question:"What does this print?",
    code:`fruits = ["apple", "banana", "cherry"]\nfor fruit in fruits:\n    print(fruit.upper())`,
    options:["apple banana cherry on one line","APPLE, BANANA, CHERRY each on their own line","apple, banana, cherry each on their own line","Error — upper() not valid here"],
    correct:1,
    hint:"Trace the loop: fruit = 'apple' → 'apple'.upper() = 'APPLE' → printed on its own line. Then repeat for 'banana' and 'cherry'. Each call to print() produces a new line.",
    explanation:"The for loop assigns each list element to fruit in turn. .upper() converts every letter to uppercase. Each print() call ends with a newline by default, so results appear on separate lines: APPLE (line 1), BANANA (line 2), CHERRY (line 3). upper() works on any string — it's a standard string method, not restricted to print().",
    defaultRunnable:`fruits = ["apple", "banana", "cherry"]\nfor fruit in fruits:\n    print(fruit.upper())`,
  },
  { id:34, topic:"Substring Check",
    question:"Which correctly checks if a string contains a substring?",
    code:`sentence = "The quick brown fox"`,
    options:['sentence.contains("quick")','"quick" in sentence','sentence.find("quick") == True','search("quick", sentence)'],
    correct:1,
    hint:'Python uses the "in" keyword directly — no method call needed. "quick" in sentence returns True or False. sentence.contains() would be Java/JavaScript syntax; it does not exist in Python.',
    explanation:'"quick" in sentence → True. This is Python\'s membership test operator, usable with strings, lists, tuples, and more. Option A (contains) doesn\'t exist in Python — that\'s Java/JavaScript. Option C: find() returns the starting index (e.g. 4) if found, or -1 if not; comparing it to True doesn\'t give a reliable boolean. Option D: search() is from the re module and requires import re.',
    defaultRunnable:`sentence = "The quick brown fox"\nprint("quick" in sentence)\nprint("slow" in sentence)\nprint(sentence.find("quick"))  # returns index, not True/False`,
  },
  { id:35, topic:"List Concatenation",
    question:"What is printed?",
    code:`a = [1, 2, 3]\nb = [4, 5, 6]\nc = a + b\nprint(c)\nprint(len(c))`,
    options:["[1, 2, 3, 4, 5, 6] and 6","[5, 7, 9] and 3","[[1,2,3],[4,5,6]] and 2","Error — can't add lists"],
    correct:0,
    hint:"The + operator on two lists joins them end-to-end (like 'ab' + 'cd' = 'abcd' for strings). It does NOT add the numbers together elementwise — that would require a loop or zip().",
    explanation:"a + b places all of a's elements followed by all of b's elements into a new list: [1, 2, 3, 4, 5, 6]. This is concatenation, not addition. Option B ([5,7,9]) would be elementwise addition — Python lists don't do that with +. len([1,2,3,4,5,6]) = 6 because the combined list has 6 elements.",
    defaultRunnable:`a = [1, 2, 3]\nb = [4, 5, 6]\nc = a + b\nprint(c)\nprint(len(c))`,
  },

  // ── Ch. 7 — Strings ──────────────────────────────────────────────────────

  { id:36, topic:"List Slicing",
    question:"What does this print?",
    code:`nums = [10, 20, 30, 40, 50]\nprint(nums[1:4])\nprint(nums[:2])\nprint(nums[::2])`,
    options:["[20,30,40], [10,20], [10,30,50]","[20,30,40], [10,20,30], [10,30,50]","[10,20,30], [10,20], [20,40]","[20,30,40], [10], [10,30,50]"],
    correct:0,
    hint:"nums[1:4]: start at index 1, stop BEFORE index 4 (indices 1,2,3 only). nums[:2]: from start, stop before index 2 (indices 0,1). nums[::2]: step=2 means every 2nd element starting from index 0 — that picks indices 0, 2, 4.",
    explanation:"nums = [10,20,30,40,50] (indices 0–4). nums[1:4]: indices 1,2,3 → [20,30,40] (index 4 excluded — the stop is always excluded). nums[:2]: indices 0,1 → [10,20]. nums[::2]: step 2 from index 0 → indices 0,2,4 → [10,30,50]. Option B is wrong because nums[:2] gives only 2 elements, not 3.",
    defaultRunnable:`nums = [10, 20, 30, 40, 50]\nprint(nums[1:4])\nprint(nums[:2])\nprint(nums[::2])\nprint(nums[::-1])  # reversed`,
  },
  { id:37, topic:"split() and strip()",
    question:"What does this code print?",
    code:`line = "  hello world  "\nwords = line.strip().split()\nprint(words)\nprint(len(words))`,
    options:['["hello", "world"] and 2','["  hello", "world  "] and 2','["hello world"] and 1',"Error"],
    correct:0,
    hint:'Step 1: line.strip() removes the leading 2 spaces and trailing 2 spaces, giving "hello world". Step 2: .split() with NO argument splits on any whitespace and trims extras — it never leaves empty strings.',
    explanation:'strip() removes leading and trailing whitespace: "  hello world  " → "hello world". Then .split() with no argument splits on any whitespace run → ["hello", "world"]. len(["hello","world"]) = 2. Option B is wrong because strip() already removed the outer spaces. Option C is wrong because split() separates the two words.',
    defaultRunnable:`line = "  hello world  "\nprint(repr(line.strip()))\nwords = line.strip().split()\nprint(words)\nprint(len(words))\nprint("a,b,c".split(","))`,
  },
  { id:38, topic:"String Methods",
    question:"What is printed?",
    code:`s = "Hello123"\nprint(s.upper())\nprint(s.isalpha())\nprint(s.isdigit())\nprint(s.isupper())\nprint(s.endswith("23"))\nprint(s.replace("Hello", "Bye"))`,
    options:["HELLO123, True, False, False, True, Bye123","HELLO123, False, False, False, True, Bye123","HELLO123, True, True, True, True, Bye123","HELLO123, False, True, False, True, Bye123"],
    correct:1,
    hint:"isalpha() and isdigit() require ALL characters to match — even one digit makes isalpha() False, and even one letter makes isdigit() False. isupper() checks whether ALL cased letters are uppercase — 'Hello' has lowercase letters.",
    explanation:'s = "Hello123". upper() → "HELLO123". isalpha() → False (digits 1,2,3 are not letters). isdigit() → False (letters H,e,l,l,o are not digits). isupper() → False (original "Hello" has lowercase e,l,l,o — isupper requires ALL letters to be uppercase). endswith("23") → True (last two chars are 2 and 3). replace("Hello","Bye") → "Bye123".',
    defaultRunnable:`s = "Hello123"\nprint(s.upper())\nprint(s.isalpha())\nprint(s.isdigit())\nprint(s.isupper())\nprint(s.endswith("23"))\nprint(s.replace("Hello", "Bye"))`,
  },
  { id:39, topic:"String Concatenation",
    question:"What is printed?",
    code:`first = "Python"\nlast  = "Quiz"\nresult = first + " " + last + "!"\nprint(result)\nprint(len(result))`,
    options:["Python Quiz! and 12","PythonQuiz! and 11","Python Quiz and 11","Python Quiz! and 11"],
    correct:0,
    hint:'Count every character in "Python Quiz!" — including the space and the exclamation mark: P-y-t-h-o-n = 6, SPACE = 1, Q-u-i-z = 4, ! = 1. Total = 6+1+4+1 = ?',
    explanation:'"Python" + " " + "Quiz" + "!" = "Python Quiz!". Counting: P(1)y(2)t(3)h(4)o(5)n(6) (7=SPACE)Q(8)u(9)i(10)z(11)!(12) = 12 characters. Watch out for option D — it also shows "Python Quiz!" but claims len = 11, forgetting to count the space.',
    defaultRunnable:`first = "Python"\nlast  = "Quiz"\nresult = first + " " + last + "!"\nprint(result)\nprint(len(result))`,
  },
  { id:40, topic:"Functions with Strings",
    question:"What does this print?",
    code:`def shout(text):\n    return text.upper() + "!!!"\n\nmessage = shout("hello")\nprint(message)`,
    options:["hello!!!","HELLO!!!","HELLO","Error — upper() only works inside print()"],
    correct:1,
    hint:'Follow the call: shout receives text = "hello". text.upper() converts every letter to uppercase → "HELLO". Then "HELLO" + "!!!" concatenates the exclamation marks. The function returns this combined string.',
    explanation:'shout("hello"): text = "hello". text.upper() → "HELLO". "HELLO" + "!!!" → "HELLO!!!". The function returns "HELLO!!!". message = "HELLO!!!". print(message) outputs HELLO!!!. upper() is a standard string method — it works anywhere on a string, not just inside print().',
    defaultRunnable:`def shout(text):\n    return text.upper() + "!!!"\n\nprint(shout("hello"))\nprint(shout("quiet"))\nprint(shout("python"))`,
  },

  // ── Ch. 8 — OOP ──────────────────────────────────────────────────────────

  { id:41, topic:"Object-Oriented Programming",
    question:"Which best describes object-oriented programming?",
    code:`class Dog:\n    def __init__(self, name):\n        self.name = name\n    def bark(self):\n        print(f"{self.name} says: Woof!")`,
    options:["Writing code with lots of functions","A style that organizes code into classes that bundle data and behavior together","Using only loops and conditions","Programming without variables"],
    correct:1,
    hint:"OOP is a programming paradigm (a style of organising code). Think about what a class contains: both data (what the object knows — attributes) and behaviour (what it can do — methods). This models real-world things.",
    explanation:"OOP organises code into classes that bundle together data (attributes, e.g. self.name) and behaviour (methods, e.g. bark()). A Dog class models a dog — it knows its name and can bark. Contrast with procedural programming, which is just a sequence of functions with separate data. OOP makes large programs easier to understand, reuse, and maintain.",
    defaultRunnable:`class Dog:\n    def __init__(self, name):\n        self.name = name\n    def bark(self):\n        print(f"{self.name} says: Woof!")\nfido = Dog("Fido")\nfido.bark()`,
  },
  { id:42, topic:"Classes and Objects",
    question:"What is the relationship between a class and an object?",
    code:`class Dog:\n    def __init__(self, name):\n        self.name = name\n\nfido  = Dog("Fido")\nbuddy = Dog("Buddy")`,
    options:["A class is an instance; an object is the blueprint","A class is the blueprint; an object is an instance created from it","They are the same thing with different names","An object holds classes inside it"],
    correct:1,
    hint:"The class is the cookie cutter — it defines the shape. An object is an actual cookie made using that cutter. Dog is defined once; fido and buddy are two separate real dogs created from it.",
    explanation:"A class is the blueprint or template — it defines what attributes and methods all instances will have. An object (instance) is a specific thing created from that blueprint. Dog is the class (written once). Dog('Fido') creates one object; Dog('Buddy') creates another. Both are Dogs with a .name attribute, but they are completely independent objects with different names.",
    defaultRunnable:`class Dog:\n    def __init__(self, name):\n        self.name = name\n\nfido  = Dog("Fido")\nbuddy = Dog("Buddy")\nprint(fido.name)\nprint(buddy.name)\nprint(type(fido))`,
  },
  { id:43, topic:"Defining a Class",
    question:"Which correctly defines a class with one attribute?",
    code:`# Correct:\nclass Car:\n    def __init__(self, color):\n        self.color = color`,
    options:["class Car() with a class-level variable","class Car: with __init__ and self.color","def class Car: — hybrid syntax","Car = class { color: 'red' } — JavaScript syntax"],
    correct:1,
    hint:"A Python class header is 'class ClassName:' with a colon (parentheses are only needed when inheriting). Instance attributes are set inside __init__ using self.attribute_name = value.",
    explanation:"class Car: is the correct header — no parentheses needed unless inheriting. The __init__ method receives self (the new object being created) plus parameters. self.color = color stores color as an attribute on that specific instance. Option A: class-level variables are shared by all instances (a different concept). Option C: def class is invalid Python syntax. Option D: that's JavaScript object literal syntax.",
    defaultRunnable:`class Car:\n    def __init__(self, color):\n        self.color = color\n\nmy_car = Car("red")\nprint(my_car.color)`,
  },
  { id:44, topic:"Encapsulation",
    question:"What does encapsulation mean in OOP?",
    code:`class BankAccount:\n    def __init__(self, balance):\n        self.__balance = balance  # private!\n\n    def get_balance(self):\n        return self.__balance`,
    options:["Hiding data inside an object and controlling access through methods","Making all variables global","Copying one class into another","Running code faster by grouping it"],
    correct:0,
    hint:"Encapsulation is about two things: (1) bundling data together with the methods that manage it, and (2) hiding internal details from the outside. The __ prefix makes __balance private — external code can't access it directly.",
    explanation:"Encapsulation means: (1) bundle data and methods together in a class, and (2) restrict direct access to internal data. __balance uses name-mangling (becomes _BankAccount__balance) to prevent direct external access. Code outside the class must go through get_balance() instead. This prevents accidental corruption, allows validation in setters, and lets you change the internal implementation without breaking code that uses the class.",
    defaultRunnable:`class BankAccount:\n    def __init__(self, balance):\n        self.__balance = balance\n    def get_balance(self):\n        return self.__balance\n\nacc = BankAccount(100)\nprint(acc.get_balance())`,
  },
  { id:45, topic:"Getters and Setters",
    question:"What are getters and setters?",
    code:`class Temperature:\n    def get_celsius(self):      # getter / accessor\n        return self.__celsius\n\n    def set_celsius(self, val): # setter / mutator\n        if val >= -273.15:\n            self.__celsius = val`,
    options:["get() and set() for dictionaries","Methods that read (getter) or modify (setter) private attributes safely","Built-in Python functions for list operations","The __init__ and __str__ methods"],
    correct:1,
    hint:"Getter = accessor = 'get me the current value of the private attribute'. Setter = mutator = 'set this attribute to a new value, with validation'. Together they enforce encapsulation by controlling how private data is read and changed.",
    explanation:"A getter (accessor) reads and returns a private attribute: get_celsius() returns self.__celsius. A setter (mutator) changes a private attribute, often with validation first: set_celsius() checks val >= -273.15 (absolute zero) before accepting it. Without setters, external code could set __celsius to -9999, which is physically impossible. Getters and setters are how encapsulation works in practice.",
    defaultRunnable:`class Temperature:\n    def __init__(self, c):\n        self.__celsius = c\n    def get_celsius(self):\n        return self.__celsius\n    def set_celsius(self, val):\n        if val >= -273.15:\n            self.__celsius = val\nt = Temperature(20)\nprint(t.get_celsius())\nt.set_celsius(25)\nprint(t.get_celsius())`,
  },
  { id:46, topic:"__init__ Method",
    question:"What is the purpose of __init__?",
    code:`class Person:\n    def __init__(self, name, age):\n        self.name = name\n        self.age  = age\n\np = Person("Alice", 30)`,
    options:["It imports the class from another file","It runs automatically when an object is created, setting up its initial attributes","It destroys the object when done","It makes the class printable"],
    correct:1,
    hint:"__init__ stands for 'initialise'. It's Python's constructor method. The instant you write Person('Alice', 30), Python creates a blank Person object and immediately calls __init__(self, 'Alice', 30) to set it up.",
    explanation:"__init__ is the constructor — it runs automatically the moment you create an instance. Person('Alice', 30): Python creates a new Person object, then calls __init__(self, 'Alice', 30). self refers to the new object. self.name = 'Alice' and self.age = 30 store the values as attributes. After __init__ finishes, p.name gives 'Alice' and p.age gives 30. The double underscores (__) mean it's a 'dunder' (magic) method with special Python behaviour.",
    defaultRunnable:`class Person:\n    def __init__(self, name, age):\n        self.name = name\n        self.age  = age\n\np = Person("Alice", 30)\nprint(p.name, p.age)`,
  },
  { id:47, topic:"__str__ Method",
    question:"What does __str__ do?",
    code:`class Point:\n    def __init__(self, x, y):\n        self.x = x\n        self.y = y\n\n    def __str__(self):\n        return f"Point({self.x}, {self.y})"\n\np = Point(3, 7)\nprint(p)  # → Point(3, 7)`,
    options:["It converts the object to an integer","It defines what print(object) displays — a human-readable string","It stores the object as a string internally","It renames the class"],
    correct:1,
    hint:"When Python encounters print(p), it needs to turn p into a string for display. It calls p.__str__() to do this. Without __str__, Python shows a useless memory address like <__main__.Point object at 0x10fa3b2e0>.",
    explanation:"__str__ defines the human-readable string representation of an object. When you print(p), Python internally calls str(p) which calls p.__str__(). The method returns f'Point({self.x}, {self.y})' → 'Point(3, 7)', which is then displayed. Without __str__, you'd see something like <__main__.Point object at 0x10fa3b2e0>. You can also use it directly: str(p) → 'Point(3, 7)'.",
    defaultRunnable:`class Point:\n    def __init__(self, x, y):\n        self.x = x\n        self.y = y\n    def __str__(self):\n        return f"Point({self.x}, {self.y})"\n\np = Point(3, 7)\nprint(p)`,
  },
  { id:48, topic:"Objects as Arguments",
    question:"What is printed?",
    code:`class Circle:\n    def __init__(self, radius):\n        self.radius = radius\n\ndef area(shape):\n    return 3.14 * shape.radius ** 2\n\nc = Circle(5)\nprint(area(c))`,
    options:["Error — objects can't be passed to functions","25.0 (radius squared only)","78.5","3.14"],
    correct:2,
    hint:"Objects are passed to functions exactly like any other value. Inside area(), the parameter shape IS the Circle object c. You can access its attributes with shape.radius. Calculate: 3.14 × (5²) = 3.14 × 25 = ?",
    explanation:"Python passes objects to functions by reference — no special syntax needed. Inside area(shape), shape is the Circle c, so shape.radius = 5. Calculation: 3.14 × (5²) = 3.14 × 25 = 78.5. Option B (25.0) would be just radius² without multiplying by 3.14. Python doesn't restrict what types a function parameter can accept — as long as the object has a .radius attribute, it works.",
    defaultRunnable:`class Circle:\n    def __init__(self, radius):\n        self.radius = radius\n\ndef area(shape):\n    return 3.14 * shape.radius ** 2\n\nc = Circle(5)\nprint(area(c))`,
  },
  { id:49, topic:"Polymorphism",
    question:"What does polymorphism mean in OOP?",
    code:`class Dog:\n    def speak(self):\n        return "Woof!"\n\nclass Cat:\n    def speak(self):\n        return "Meow!"\n\ndef make_sound(animal):\n    print(animal.speak())\n\nmake_sound(Dog())  # Woof!\nmake_sound(Cat())  # Meow!`,
    options:["All classes must have the same methods","A class can inherit from multiple parents","Different objects can respond to the same method call in their own way","A function can only accept one type of argument"],
    correct:2,
    hint:'"Poly" = many, "morph" = form. The same method call (animal.speak()) produces different output depending on the TYPE of object passed in. Dog and Cat both have speak(), but they do different things.',
    explanation:'Polymorphism means "many forms." The same operation (speak()) produces different results based on the actual type of the object. make_sound(Dog()) → animal.speak() calls Dog\'s speak → "Woof!". make_sound(Cat()) → animal.speak() calls Cat\'s speak → "Meow!". The make_sound function doesn\'t need to know which type it received — it just calls speak() and polymorphism handles the rest. This lets you write flexible, extensible code.',
    defaultRunnable:`class Dog:\n    def speak(self):\n        return "Woof!"\nclass Cat:\n    def speak(self):\n        return "Meow!"\n\nfor animal in [Dog(), Cat(), Dog()]:\n    print(animal.speak())`,
  },
  { id:50, topic:"Inheritance",
    question:"What does inheritance allow?",
    code:`class Animal:\n    def __init__(self, name):\n        self.name = name\n    def eat(self):\n        print(f"{self.name} is eating")\n\nclass Dog(Animal):        # Dog inherits from Animal\n    def bark(self):\n        print("Woof!")\n\nd = Dog("Rex")\nd.eat()   # inherited from Animal\nd.bark()  # defined in Dog`,
    options:["Copying code from one file to another","A class to acquire the attributes and methods of another class","Making two classes identical","Running a function automatically"],
    correct:1,
    hint:"class Dog(Animal) means Dog inherits from Animal. Dog automatically gets ALL of Animal's attributes and methods for free. Dog only defines what's new or different — in this case, just bark().",
    explanation:"Inheritance lets a child class (Dog) automatically acquire all attributes and methods from a parent class (Animal). Dog defines only bark() — but it also inherits __init__(self, name) and eat() from Animal without copy-pasting them. d = Dog('Rex') calls Animal's __init__ (since Dog has none of its own). d.eat() works because Dog inherits eat(). d.bark() works because Dog defines it. Inheritance promotes code reuse and creates an 'is-a' relationship: a Dog IS-A Animal.",
    defaultRunnable:`class Animal:\n    def __init__(self, name):\n        self.name = name\n    def eat(self):\n        print(f"{self.name} is eating")\n\nclass Dog(Animal):\n    def bark(self):\n        print("Woof!")\n\nd = Dog("Rex")\nd.eat()\nd.bark()`,
  },
  { id:51, topic:"Base Class vs Subclass",
    question:"In class Dog(Animal):, what are Dog and Animal?",
    code:`class Animal:        # base class (parent / superclass)\n    def breathe(self):\n        print("breathing")\n\nclass Dog(Animal):   # subclass (child / derived class)\n    def bark(self):\n        print("woof")`,
    options:["Animal is the subclass; Dog is the base class","They are both base classes","Animal is the base class (parent); Dog is the subclass (child)","Dog and Animal are both subclasses of Python's object class only"],
    correct:2,
    hint:"In 'class Dog(Animal)', read it as 'Dog inherits FROM Animal'. The class listed in parentheses is the parent/base class — the one being inherited from. The class being defined (Dog) is the child/subclass.",
    explanation:"The base class (parent/superclass) is the class being inherited FROM — Animal. It provides base functionality. The subclass (child/derived class) is the class that inherits — Dog. It extends or overrides the base class. Key terms: Animal = base class = parent class = superclass. Dog = subclass = child class = derived class. isinstance(d, Animal) returns True because Dog inherits from Animal — every Dog IS-A Animal.",
    defaultRunnable:`class Animal:\n    def breathe(self):\n        print("breathing")\n\nclass Dog(Animal):\n    def bark(self):\n        print("woof")\n\nd = Dog()\nd.breathe()  # from Animal\nd.bark()     # from Dog\nprint(isinstance(d, Animal))  # True`,
  },
  // ── Ch. 1 Basics — extra questions ───────────────────────────────────────
  { id:52, topic:"Type Conversion",
    question:"What is printed?",
    code:`x = "42"\ny = int(x) + 8\nprint(y)`,
    options:["50","428","TypeError — can't add string to int","'50'"],
    correct:0,
    hint:"int() converts the string '42' to the integer 42 first. Then + performs arithmetic on two integers.",
    explanation:"int('42') converts to 42. 42 + 8 = 50. Both operands are now integers so + is arithmetic, not concatenation. Option B would result from '42' + '8' (string concatenation without int()). Option C would happen if you tried to add '42' + 8 without converting first.",
    defaultRunnable:`x = "42"\ny = int(x) + 8\nprint(y)\nprint(type(y))\n# print("42" + 8)  ← TypeError`,
  },
  { id:53, topic:"String Repetition",
    question:"What does this print?",
    code:`s = "ha" * 3\nprint(s)`,
    options:["hahaha","ha ha ha","ha3","Error — * only works with numbers"],
    correct:0,
    hint:"The * operator with a string and an integer repeats the string n times end-to-end. No spaces or separators are added.",
    explanation:"'ha' * 3 = 'ha' + 'ha' + 'ha' = 'hahaha'. String repetition works just like list repetition: 'ab' * 3 = 'ababab'. No spaces are inserted between copies.",
    defaultRunnable:`s = "ha" * 3\nprint(s)\nprint("abc" * 2)\nprint("-" * 20)`,
  },
  { id:54, topic:"Variable Swap",
    question:"What is printed?",
    code:`a, b = 10, 20\na, b = b, a\nprint(a, b)`,
    options:["10 20","20 10","10 10","20 20"],
    correct:1,
    hint:"Python evaluates the RIGHT side first as a tuple (b, a) = (20, 10), then assigns both simultaneously. No values are lost.",
    explanation:"a, b = 10, 20 sets a=10, b=20. Then a, b = b, a: the right side (b, a) = (20, 10) is evaluated first as a tuple, then unpacked: a=20, b=10. print(20, 10) → '20 10'. This is Python's built-in swap — no temporary variable needed.",
    defaultRunnable:`a, b = 10, 20\na, b = b, a\nprint(a, b)\nx, y = "hello", "world"\nx, y = y, x\nprint(x, y)`,
  },
  { id:55, topic:"print() sep Argument",
    question:"What is printed?",
    code:`print("A", "B", "C", sep="-")`,
    options:["A B C","A-B-C","ABC","A, B, C"],
    correct:1,
    hint:"print() accepts a sep= keyword argument that sets the separator between values. The default separator is a single space.",
    explanation:"print() joins its arguments using sep. Default sep=' ' gives 'A B C'. With sep='-': 'A-B-C'. You can also use sep='' for no separator or sep='\\n' to print each on its own line.",
    defaultRunnable:`print("A", "B", "C", sep="-")\nprint("A", "B", "C")\nprint("A", "B", "C", sep="")\nprint(1, 2, 3, sep=", ")`,
  },

  // ── Ch. 2 Logic — extra questions ─────────────────────────────────────────
  { id:56, topic:"Comparison Operators",
    question:"What is printed?",
    code:`x = 10\nprint(x != 5)\nprint(x >= 10)\nprint(x < 10)`,
    options:["True True False","False True True","True False True","True True True"],
    correct:0,
    hint:"!= means not equal, >= means greater than OR equal to, < means strictly less than. Evaluate each with x = 10.",
    explanation:"x = 10. x != 5 → True (10 ≠ 5). x >= 10 → True (10 ≥ 10, the equal case counts). x < 10 → False (10 is not strictly less than 10). Three separate print() calls produce three lines of output.",
    defaultRunnable:`x = 10\nprint(x != 5)\nprint(x >= 10)\nprint(x < 10)\nprint(x == 10)\nprint(x <= 10)`,
  },
  { id:57, topic:"not Operator",
    question:"What is printed?",
    code:`x = False\ny = not x\nprint(y)\nprint(not True)`,
    options:["True then False","False then True","True then True","False then False"],
    correct:0,
    hint:"'not' flips a boolean: not False = True, not True = False. There are two separate print() calls.",
    explanation:"y = not False = True. print(y) → True. print(not True) → False. Output: True on line 1, False on line 2. The 'not' operator always produces the opposite boolean value.",
    defaultRunnable:`x = False\ny = not x\nprint(y)\nprint(not True)\nprint(not 0)\nprint(not "hi")`,
  },
  { id:58, topic:"Chained Comparisons",
    question:"What is printed?",
    code:`x = 5\nprint(1 < x < 10)\nprint(10 < x < 20)`,
    options:["True then False","False then True","True then True","False then False"],
    correct:0,
    hint:"Python allows chained comparisons: 1 < x < 10 means (1 < x) and (x < 10). Both parts must be True for the whole expression to be True.",
    explanation:"1 < 5 < 10: 1 < 5 is True AND 5 < 10 is True → True. 10 < 5 < 20: 10 < 5 is False → short-circuits to False without checking the rest. Two print() calls: True then False.",
    defaultRunnable:`x = 5\nprint(1 < x < 10)\nprint(10 < x < 20)\nprint(1 <= x <= 5)`,
  },
  { id:59, topic:"Truthiness",
    question:"What is printed?",
    code:`print(bool(0))\nprint(bool(""))\nprint(bool(42))\nprint(bool("hello"))`,
    options:["False False True True","True True False False","False True False True","True False True False"],
    correct:0,
    hint:"In Python: 0, '' (empty string), [] (empty list), and None are falsy. Everything else is truthy.",
    explanation:"bool(0) → False (zero is falsy). bool('') → False (empty string is falsy). bool(42) → True (non-zero is truthy). bool('hello') → True (non-empty string is truthy). These rules apply whenever Python evaluates a value as a condition.",
    defaultRunnable:`print(bool(0))\nprint(bool(""))\nprint(bool(42))\nprint(bool("hello"))\nprint(bool([]))\nprint(bool([1,2,3]))\nprint(bool(None))`,
  },

  // ── Ch. 3 If Statements — extra questions ─────────────────────────────────
  { id:60, topic:"elif Chain",
    question:"What is printed?",
    code:`score = 75\nif score >= 90:\n    print("A")\nelif score >= 80:\n    print("B")\nelif score >= 70:\n    print("C")\nelse:\n    print("F")`,
    options:["A","B","C","F"],
    correct:2,
    hint:"Python checks conditions top-to-bottom and stops at the FIRST True condition. Is 75 ≥ 90? Is 75 ≥ 80? Is 75 ≥ 70?",
    explanation:"score = 75. 75 >= 90? No. 75 >= 80? No. 75 >= 70? Yes → prints 'C'. Once a condition is True, all remaining elif/else branches are skipped. The else would only run if all conditions were False.",
    defaultRunnable:`score = 75\nif score >= 90:\n    print("A")\nelif score >= 80:\n    print("B")\nelif score >= 70:\n    print("C")\nelse:\n    print("F")`,
  },
  { id:61, topic:"Nested if",
    question:"What is printed?",
    code:`x = 15\nif x > 10:\n    if x > 20:\n        print("big")\n    else:\n        print("medium")\nelse:\n    print("small")`,
    options:["big","medium","small","big medium"],
    correct:1,
    hint:"Trace from outside in: does x > 10 pass? If yes, evaluate the inner if: does x > 20 pass?",
    explanation:"x = 15. Outer: 15 > 10 → True, enter outer block. Inner: 15 > 20 → False → print('medium'). The outer else is never reached. Only ONE branch executes — 'big medium' is impossible since inner if/else runs exactly one branch.",
    defaultRunnable:`x = 15\nif x > 10:\n    if x > 20:\n        print("big")\n    else:\n        print("medium")\nelse:\n    print("small")`,
  },
  { id:62, topic:"Conditional Expression",
    question:"What is printed?",
    code:`age = 20\nstatus = "adult" if age >= 18 else "minor"\nprint(status)`,
    options:["adult","minor","Error — invalid syntax","None"],
    correct:0,
    hint:"Python's conditional expression: value_if_true if condition else value_if_false. It evaluates to one of the two values based on the condition.",
    explanation:"age = 20. 20 >= 18 is True → status = 'adult'. This is equivalent to: if age >= 18: status = 'adult' else: status = 'minor' — but written as one line. The syntax is valid Python (sometimes called a ternary expression).",
    defaultRunnable:`age = 20\nstatus = "adult" if age >= 18 else "minor"\nprint(status)\nresult = "even" if 4 % 2 == 0 else "odd"\nprint(result)`,
  },
  { id:63, topic:"Indentation Rules",
    question:"What happens when you run this code?",
    code:`x = 5\nif x > 3:\nprint("yes")`,
    options:["Prints yes","Prints nothing","IndentationError","NameError"],
    correct:2,
    hint:"Python uses indentation to define code blocks. The body of an if statement MUST be indented or Python raises an error.",
    explanation:"print('yes') is at column 0 — not indented inside the if. Python raises IndentationError: expected an indented block after 'if' statement. Indentation is syntax in Python, not just style. Every if/for/while/def/class body must be indented by the same amount.",
    defaultRunnable:`x = 5\nif x > 3:\n    print("yes")  # correct — indented\n# removing the indent causes IndentationError`,
  },

  // ── Ch. 4 Loops — extra questions ─────────────────────────────────────────
  { id:64, topic:"break Statement",
    question:"What is printed?",
    code:`for i in range(10):\n    if i == 5:\n        break\n    print(i)`,
    options:["0 1 2 3 4","0 1 2 3 4 5","1 2 3 4 5","0 1 2 3 4 5 6 7 8 9"],
    correct:0,
    hint:"break immediately exits the loop entirely. When i == 5, break runs BEFORE print(i), so 5 is never printed.",
    explanation:"i=0: print 0 ... i=4: print 4. i=5: if True → break — loop exits before print(i). Output: 0,1,2,3,4 each on a new line. Option B is wrong because break fires before 5 is printed. break exits the loop completely (no more iterations).",
    defaultRunnable:`for i in range(10):\n    if i == 5:\n        break\n    print(i)\nprint("after loop")`,
  },
  { id:65, topic:"continue Statement",
    question:"What is printed?",
    code:`for i in range(5):\n    if i == 2:\n        continue\n    print(i)`,
    options:["0 1 3 4","0 1 2 3 4","0 1 2 4","1 3 4"],
    correct:0,
    hint:"continue skips the rest of the current iteration and moves to the NEXT one. The loop does NOT exit — it keeps running.",
    explanation:"i=0: print 0. i=1: print 1. i=2: continue → jump to i=3 (print(2) is skipped). i=3: print 3. i=4: print 4. Output: 0,1,3,4. Only i=2 is skipped. Unlike break, continue doesn't end the loop.",
    defaultRunnable:`for i in range(5):\n    if i == 2:\n        continue\n    print(i)\nprint("loop finished")`,
  },
  { id:66, topic:"range() Step",
    question:"What is printed?",
    code:`for i in range(0, 10, 3):\n    print(i)`,
    options:["0 3 6 9","0 3 6","0 3 6 9 12","3 6 9"],
    correct:0,
    hint:"range(start, stop, step) generates numbers from start up to (but not including) stop, incrementing by step each time.",
    explanation:"range(0, 10, 3): 0, 3, 6, 9. The next would be 12 which is ≥ 10, so it stops. Option B stops at 6 (wrong). Option C includes 12 which exceeds the stop value. Option D skips the starting value 0.",
    defaultRunnable:`for i in range(0, 10, 3):\n    print(i)\nprint(list(range(0, 10, 3)))\nprint(list(range(10, 0, -2)))`,
  },
  { id:67, topic:"enumerate()",
    question:"What does this print?",
    code:`fruits = ["apple", "banana", "cherry"]\nfor i, fruit in enumerate(fruits):\n    print(i, fruit)`,
    options:["0 apple / 1 banana / 2 cherry (each on own line)","1 apple / 2 banana / 3 cherry (each on own line)","apple 0 / banana 1 / cherry 2 (each on own line)","Error — enumerate() not valid here"],
    correct:0,
    hint:"enumerate() yields (index, value) pairs starting at index 0. The loop unpacks each pair into i and fruit.",
    explanation:"enumerate(fruits) produces (0,'apple'), (1,'banana'), (2,'cherry'). Each tuple is unpacked into i and fruit. print(i, fruit) outputs '0 apple', '1 banana', '2 cherry' — each on its own line. Indexing starts at 0, not 1.",
    defaultRunnable:`fruits = ["apple", "banana", "cherry"]\nfor i, fruit in enumerate(fruits):\n    print(i, fruit)\nfor i, fruit in enumerate(fruits, start=1):\n    print(i, fruit)`,
  },

  // ── Ch. 5 Lists & Funcs — extra questions ─────────────────────────────────
  { id:68, topic:"Default Parameters",
    question:"What is printed?",
    code:`def greet(name, msg="Hello"):\n    print(f"{msg}, {name}!")\n\ngreet("Alice")\ngreet("Bob", "Hi")`,
    options:["Hello, Alice! then Hello, Bob!","Hello, Alice! then Hi, Bob!","Error — msg is required","Hi, Alice! then Hi, Bob!"],
    correct:1,
    hint:"Default parameter values are used only when no argument is passed for that parameter. An explicit argument always overrides the default.",
    explanation:"greet('Alice') → msg uses default 'Hello' → prints 'Hello, Alice!'. greet('Bob', 'Hi') → msg is overridden to 'Hi' → prints 'Hi, Bob!'. Default parameters must come after required parameters in the definition.",
    defaultRunnable:`def greet(name, msg="Hello"):\n    print(f"{msg}, {name}!")\n\ngreet("Alice")\ngreet("Bob", "Hi")\ngreet("Charlie", msg="Yo")`,
  },
  { id:69, topic:"List Methods",
    question:"What is printed?",
    code:`nums = [3, 1, 4, 1, 5]\nnums.append(9)\nnums.sort()\nprint(nums)`,
    options:["[1, 1, 3, 4, 5, 9]","[3, 1, 4, 1, 5, 9]","[9, 5, 4, 3, 1, 1]","[1, 1, 3, 4, 5]"],
    correct:0,
    hint:"append(x) adds x to the END. sort() reorders in-place ascending. Both modify the list directly.",
    explanation:"Start: [3,1,4,1,5]. append(9) → [3,1,4,1,5,9]. sort() → [1,1,3,4,5,9] ascending. Option B shows only append applied (no sort). Option C is descending (needs sort(reverse=True)). Option D is missing the 9 (append was skipped).",
    defaultRunnable:`nums = [3, 1, 4, 1, 5]\nnums.append(9)\nprint(nums)\nnums.sort()\nprint(nums)\nnums.sort(reverse=True)\nprint(nums)`,
  },
  { id:70, topic:"Returning Multiple Values",
    question:"What is printed?",
    code:`def min_max(nums):\n    return min(nums), max(nums)\n\nlo, hi = min_max([5, 2, 8, 1, 9])\nprint(lo, hi)`,
    options:["1 9","9 1","(1, 9)","1, 9"],
    correct:0,
    hint:"A function can return multiple values as a tuple. Unpacking with lo, hi = ... assigns each. print(lo, hi) prints them space-separated.",
    explanation:"min([5,2,8,1,9])=1, max=9. Returns tuple (1,9). lo, hi = (1,9) unpacks: lo=1, hi=9. print(lo, hi) → '1 9' (space-separated, no brackets). Option C shows tuple brackets — that would need print((lo,hi)). Option D shows a comma — that would need print(f'{lo}, {hi}').",
    defaultRunnable:`def min_max(nums):\n    return min(nums), max(nums)\n\nlo, hi = min_max([5, 2, 8, 1, 9])\nprint(lo, hi)\nresult = min_max([3, 7, 1])\nprint(result)`,
  },
  { id:71, topic:"List Comprehension",
    question:"What is printed?",
    code:`squares = [x**2 for x in range(1, 6)]\nprint(squares)`,
    options:["[1, 4, 9, 16, 25]","[2, 4, 6, 8, 10]","[1, 2, 3, 4, 5]","[0, 1, 4, 9, 16]"],
    correct:0,
    hint:"List comprehension [expression for var in iterable] evaluates the expression for each value and collects the results. x**2 means x squared.",
    explanation:"range(1,6) = 1,2,3,4,5. x**2 squares each: 1→1, 2→4, 3→9, 4→16, 5→25. Result: [1,4,9,16,25]. Option B doubles (x*2). Option C just collects the range values. Option D starts from 0 (range(0,5)).",
    defaultRunnable:`squares = [x**2 for x in range(1, 6)]\nprint(squares)\nevens = [x for x in range(10) if x % 2 == 0]\nprint(evens)\nwords = ["hello", "world"]\ncaps = [w.upper() for w in words]\nprint(caps)`,
  },

  // ── Ch. 6 Lists Deep Dive — extra questions ────────────────────────────────
  { id:72, topic:"pop() and remove()",
    question:"What is printed?",
    code:`items = [10, 20, 30, 40]\nitems.pop()\nitems.remove(20)\nprint(items)`,
    options:["[10, 30]","[10, 20, 30]","[20, 30, 40]","[10, 20, 40]"],
    correct:0,
    hint:"pop() with no argument removes the LAST element. remove(x) finds and removes the FIRST occurrence of the value x.",
    explanation:"Start: [10,20,30,40]. pop() removes 40 (last) → [10,20,30]. remove(20) finds value 20 and removes it → [10,30]. Option B shows only pop applied. Option D is wrong — remove(20) targets by value, not position.",
    defaultRunnable:`items = [10, 20, 30, 40]\nprint(items.pop())\nprint(items)\nitems.remove(20)\nprint(items)\nitems2 = [1,2,3,4]\nprint(items2.pop(1))`,
  },
  { id:73, topic:"2D Lists",
    question:"What is printed?",
    code:`grid = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]\nprint(grid[1][2])\nprint(grid[0][0])`,
    options:["6 then 1","5 then 1","6 then 4","5 then 2"],
    correct:0,
    hint:"grid[row][col]: first index picks the inner list (row), second picks an element in that list (column). All indices start at 0.",
    explanation:"grid[1] = [4,5,6] (second row, index 1). grid[1][2] = 6 (third element of that row, index 2). grid[0] = [1,2,3]. grid[0][0] = 1. Two print() calls: 6 then 1.",
    defaultRunnable:`grid = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]\nprint(grid[1][2])\nprint(grid[0][0])\nprint(grid[2][1])\nprint(grid[0])`,
  },
  { id:74, topic:"insert() and count()",
    question:"What is printed?",
    code:`nums = [1, 2, 2, 3, 4]\nnums.insert(2, 99)\nprint(nums)\nprint(nums.count(2))`,
    options:["[1, 2, 99, 2, 3, 4] then 2","[1, 2, 2, 99, 3, 4] then 2","[99, 1, 2, 2, 3, 4] then 2","[1, 2, 99, 2, 3, 4] then 1"],
    correct:0,
    hint:"insert(i, x) inserts x BEFORE index i. count(x) counts how many times x appears in the modified list.",
    explanation:"nums = [1,2,2,3,4]. insert(2, 99) inserts 99 before index 2 → [1,2,99,2,3,4]. count(2) counts value 2: appears at index 1 and index 3 → 2. Option B inserts at wrong position. Option D miscounts — 2 still appears twice after insertion.",
    defaultRunnable:`nums = [1, 2, 2, 3, 4]\nnums.insert(2, 99)\nprint(nums)\nprint(nums.count(2))\nprint(nums.index(99))`,
  },

  // ── Ch. 7 Strings — extra questions ───────────────────────────────────────
  { id:75, topic:"find() Method",
    question:"What is printed?",
    code:`text = "Hello, World!"\nprint(text.find("World"))\nprint(text.find("Python"))`,
    options:["7 then -1","7 then 0","6 then -1","True then False"],
    correct:0,
    hint:"find() returns the starting index if found, or -1 if not found. Count: H(0)e(1)l(2)l(3)o(4),(5) (6)W(7)...",
    explanation:"'Hello, World!': W is at index 7 (H=0,e=1,l=2,l=3,o=4,,=5,space=6,W=7). find('World') → 7. 'Python' is not in the string → find('Python') → -1. Option D shows the result of the 'in' operator (True/False), not find().",
    defaultRunnable:`text = "Hello, World!"\nprint(text.find("World"))\nprint(text.find("Python"))\nprint(text.find("l"))\nprint(text.rfind("l"))\nprint("World" in text)`,
  },
  { id:76, topic:"String Immutability",
    question:"What happens when this code runs?",
    code:`s = "hello"\ns[0] = "H"\nprint(s)`,
    options:["Prints Hello","Prints hello","TypeError","AttributeError"],
    correct:2,
    hint:"Strings in Python are IMMUTABLE — you cannot change individual characters by index. Attempting to do so raises a TypeError.",
    explanation:"s[0] = 'H' raises TypeError: 'str' object does not support item assignment. Strings cannot be modified after creation. To change a string, create a new one: s = 'H' + s[1:] or s = s.capitalize() or s = s.replace('h','H').",
    defaultRunnable:`s = "hello"\n# s[0] = "H"  ← TypeError\ns2 = "H" + s[1:]\nprint(s2)\ns3 = s.capitalize()\nprint(s3)\ns4 = s.replace("h", "H")\nprint(s4)`,
  },
  { id:77, topic:"f-string Expressions",
    question:"What is printed?",
    code:`x = 4\ny = 3\nprint(f"{x} + {y} = {x + y}")`,
    options:["4 + 3 = 7","x + y = x + y","x + y = 7","4 + 3 = x + y"],
    correct:0,
    hint:"Inside an f-string, anything in {} is evaluated as a Python expression. Variable names are replaced with their values and expressions are computed.",
    explanation:"f-strings evaluate curly-brace expressions: {x}→4, {y}→3, {x+y}→7. Output: '4 + 3 = 7'. The variable names themselves are not printed — only their values. Option B would be a plain string (no f-prefix): the braces would print literally.",
    defaultRunnable:`x = 4\ny = 3\nprint(f"{x} + {y} = {x + y}")\nname = "Alice"\nage = 25\nprint(f"My name is {name} and twice my age is {age * 2}")`,
  },
  { id:78, topic:"startswith / endswith / count",
    question:"What is printed?",
    code:`s = "banana"\nprint(s.startswith("ban"))\nprint(s.endswith("na"))\nprint(s.count("a"))`,
    options:["True True 3","True True 2","False True 3","True False 3"],
    correct:0,
    hint:"startswith/endswith check prefix/suffix and return True/False. count(sub) counts how many times sub appears in the string.",
    explanation:"'banana'.startswith('ban') → True. .endswith('na') → True. .count('a'): b-A-n-A-n-A → 3 occurrences (positions 1, 3, 5). Option B has count=2 (off by one). Option C says startswith('ban') is False (it is True). Option D says endswith('na') is False (it is True).",
    defaultRunnable:`s = "banana"\nprint(s.startswith("ban"))\nprint(s.endswith("na"))\nprint(s.count("a"))\nprint(s.count("an"))\nprint(s.startswith("apple"))`,
  },

  // ── Ch. 8 OOP — extra questions ───────────────────────────────────────────
  { id:79, topic:"super()",
    question:"What is printed?",
    code:`class Animal:\n    def __init__(self, name):\n        self.name = name\n\nclass Dog(Animal):\n    def __init__(self, name, breed):\n        super().__init__(name)\n        self.breed = breed\n\nd = Dog("Rex", "Lab")\nprint(d.name, d.breed)`,
    options:["Rex Lab","Error — name not defined in Dog","None Lab","Rex None"],
    correct:0,
    hint:"super().__init__() calls the PARENT class's __init__, allowing you to reuse its setup code. Without it, self.name would never be assigned.",
    explanation:"Dog.__init__ calls super().__init__(name) which runs Animal.__init__(self, 'Rex'), setting self.name = 'Rex'. Then self.breed = 'Lab'. print(d.name, d.breed) → 'Rex Lab'. Without super(), AttributeError would occur because self.name was never set.",
    defaultRunnable:`class Animal:\n    def __init__(self, name):\n        self.name = name\n\nclass Dog(Animal):\n    def __init__(self, name, breed):\n        super().__init__(name)\n        self.breed = breed\n    def info(self):\n        return f"{self.name} ({self.breed})"\n\nd = Dog("Rex", "Lab")\nprint(d.info())`,
  },
  { id:80, topic:"Method Overriding",
    question:"What is printed?",
    code:`class Shape:\n    def area(self):\n        return 0\n\nclass Square(Shape):\n    def __init__(self, side):\n        self.side = side\n    def area(self):\n        return self.side ** 2\n\ns = Square(4)\nprint(s.area())`,
    options:["16","0","8","Error — area() defined twice"],
    correct:0,
    hint:"When a subclass defines a method with the same name as the parent, the subclass version OVERRIDES the parent. Python calls the most specific version.",
    explanation:"Square defines area() overriding Shape's area(). s.area() calls Square.area() (not Shape.area()). 4 ** 2 = 16. Option B (0) would result if Shape.area() were called. Defining a method with the same name is valid — it's deliberate overriding.",
    defaultRunnable:`class Shape:\n    def area(self):\n        return 0\n\nclass Square(Shape):\n    def __init__(self, side):\n        self.side = side\n    def area(self):\n        return self.side ** 2\n\nclass Circle(Shape):\n    def __init__(self, r):\n        self.r = r\n    def area(self):\n        return 3.14159 * self.r ** 2\n\nfor shape in [Square(4), Circle(3)]:\n    print(shape.area())`,
  },
  { id:81, topic:"isinstance()",
    question:"What is printed?",
    code:`class Animal: pass\nclass Dog(Animal): pass\n\nd = Dog()\nprint(isinstance(d, Dog))\nprint(isinstance(d, Animal))\nprint(isinstance(d, str))`,
    options:["True True False","True False False","False True False","True True True"],
    correct:0,
    hint:"isinstance(obj, cls) returns True if obj is an instance of cls OR any of its parent classes. A Dog IS-A Animal through inheritance.",
    explanation:"d is a Dog → isinstance(d, Dog) = True. Dog inherits from Animal → isinstance(d, Animal) = True. d is not a str → isinstance(d, str) = False. isinstance() respects the inheritance chain, unlike type() == cls which is exact.",
    defaultRunnable:`class Animal: pass\nclass Dog(Animal): pass\n\nd = Dog()\nprint(isinstance(d, Dog))\nprint(isinstance(d, Animal))\nprint(isinstance(d, str))\nprint(type(d) == Dog)\nprint(type(d) == Animal)`,
  },
  { id:82, topic:"Class Variables",
    question:"What is printed?",
    code:`class Counter:\n    count = 0\n    def __init__(self):\n        Counter.count += 1\n\nc1 = Counter()\nc2 = Counter()\nc3 = Counter()\nprint(Counter.count)`,
    options:["3","1","0","Error"],
    correct:0,
    hint:"A class variable is defined outside __init__ and is SHARED by all instances. Each time Counter() is called, __init__ increments the shared Counter.count.",
    explanation:"Counter.count = 0 is a class variable shared across all instances. Each Counter() call runs __init__, incrementing Counter.count by 1. After three instantiations: Counter.count = 3. Contrast with instance variables (self.x = ...) which are unique per object.",
    defaultRunnable:`class Counter:\n    count = 0\n    def __init__(self):\n        Counter.count += 1\n\nc1 = Counter()\nc2 = Counter()\nc3 = Counter()\nprint(Counter.count)\nprint(c1.count)`,
  },

];