export const ALL_QUESTIONS = [
  { id:1, topic:"Syntax Errors",
    question:"Which of the following would cause a syntax error?",
    code:`# Which line has a syntax error?\nA: print("Hello")\nB: x = 5 + 3\nC: if x = 5:\nD: y = int("10")`,
    options:['print("Hello")', "x = 5 + 3", "if x = 5:", 'y = int("10")'],
    correct:2,
    hint:"Think about what = does in Python vs ==",
    explanation:'if x = 5: is a syntax error because = is assignment, not comparison. Use == to compare.',
    defaultRunnable:`x = 5\nif x == 5:\n    print("Correct operator!")\n# if x = 5:  ← SyntaxError`,
  },
  { id:2, topic:"Pseudocode & Algorithms",
    question:"What best describes pseudocode?",
    code:`# PSEUDOCODE (planning):\n# GET user's age\n# IF age >= 18 THEN\n#     PRINT "Adult"\n# ELSE\n#     PRINT "Minor"\n\n# REAL PYTHON:\nage = 20\nif age >= 18:\n    print("Adult")`,
    options:["A programming language used before Python","Informal steps describing an algorithm in plain language","Python code with lots of comments","A type of flowchart diagram"],
    correct:1,
    hint:'The word "pseudo" means fake or informal',
    explanation:"Pseudocode is informal, readable language used to plan an algorithm before writing real code. No strict syntax — the goal is clarity of logic.",
    defaultRunnable:`# Pseudocode → Python:\n# GET two numbers, PRINT the larger\na, b = 8, 3\nif a > b: print(a, "is larger")\nelif b > a: print(b, "is larger")\nelse: print("Equal")`,
  },
  { id:3, topic:"Escape Characters",
    question:'What does print("Line1\\nLine2\\tEnd") output?',
    code:`print("Line1\\nLine2\\tEnd")`,
    options:['Prints literally: Line1\\nLine2\\tEnd',"Line1, newline, Line2, tab, then End","Line1Line2End on one line","SyntaxError"],
    correct:1,
    hint:"The backslash \\ creates special invisible characters",
    explanation:"\\n is a newline and \\t is a tab. These escape sequences represent characters that can't be typed directly.",
    defaultRunnable:`print("Line1\\nLine2\\tEnd")\nprint("She said \\"hello\\"")\nprint("A\\nB\\nC")\nprint("Col1\\tCol2\\tCol3")`,
  },
  { id:4, topic:"print() end Argument",
    question:"What is the output?",
    code:`print("Hello", end=" ")\nprint("World", end="!")\nprint()`,
    options:["Hello\\nWorld!\\n","Hello World!","Hello\\nWorld!","HelloWorld!"],
    correct:1,
    hint:"The end parameter replaces the default newline at the end of print()",
    explanation:'By default print() ends with \\n. end=" " replaces that with a space. The final print() just outputs a newline.',
    defaultRunnable:`print("Hello", end=" ")\nprint("World", end="!")\nprint()\nfor i in range(5):\n    print(i, end=", ")`,
  },
  { id:5, topic:"int() Function",
    question:"What does int(3.99) return?",
    code:`print(int(3.99))\nprint(int(-3.9))\nprint(int("42"))`,
    options:["4 (rounds up)","3 (truncates toward zero)","-4","Error"],
    correct:1,
    hint:"int() chops the decimal off — it does NOT round",
    explanation:"int() truncates toward zero. int(3.99)→3. int(-3.9)→-3 (not -4). Use round() for rounding.",
    defaultRunnable:`print(int(3.99))   # 3\nprint(int(-3.9))  # -3\nprint(round(3.99)) # 4\nprint(int("42"))   # 42`,
  },
  { id:6, topic:"Math Expressions",
    question:"What is the result of this expression?",
    code:`result = 10 + 2 ** 3 * 2 - 6 / 3\nprint(result)`,
    options:["24.0","22.0","18.0","20.0"],
    correct:0,
    hint:"Use PEMDAS: ** first, then * and /, then + and -",
    explanation:"2**3=8, 8*2=16, 6/3=2.0, 10+16=26, 26-2.0=24.0. Division always returns a float.",
    fillBlankAnswer:"24.0",
    defaultRunnable:`result = 10 + 2 ** 3 * 2 - 6 / 3\nprint(result)\nstep1 = 2 ** 3\nstep2 = step1 * 2\nstep3 = 6 / 3\nstep4 = 10 + step2 - step3\nprint(step4)`,
  },
  { id:7, topic:"User Input",
    question:"A user types 98.6. Which line correctly stores it as a number?",
    code:`# User types: 98.6\nA: x = input("Temp: ")\nB: x = int(input("Temp: "))\nC: x = float(input("Temp: "))\nD: x = str(input("Temp: "))`,
    options:['input() — stores as string "98.6"',"int(input()) — crashes on 98.6","float(input()) — stores as 98.6 ✓","str(input()) — same as no conversion"],
    correct:2,
    hint:"input() always returns a string, no matter what the user types",
    explanation:"input() always returns a string. float() converts it to a float. int() would crash on '98.6'.",
    defaultRunnable:`raw = "98.6"\nprint(type(raw), raw)\nprint(type(float(raw)), float(raw))\nprint(type(int(float(raw))), int(float(raw)))`,
  },
  { id:8, topic:"Formatting Floats",
    question:"What does this f-string print?",
    code:`pi = 3.14159\nprint(f"Pi is {pi:.2f} and {pi:.4f}")`,
    options:["Pi is 3.14159 and 3.14159","Pi is 3.14 and 3.1416","Pi is 3 and 3.14","SyntaxError — invalid format"],
    correct:1,
    hint:":.2f means: format as float with 2 decimal places",
    explanation:":.2f formats with 2 decimal places. :.4f uses 4 — and rounds: 3.14159 → 3.1416.",
    defaultRunnable:`pi = 3.14159265\nprint(f"2dp: {pi:.2f}")\nprint(f"4dp: {pi:.4f}")\nprice = 4.5\nprint(f"Price: \${price:.2f}")\nbig = 1234567.89\nprint(f"Big: {big:,.2f}")`,
  },
  { id:9, topic:"Boolean Type",
    question:"Which of these is an actual bool type?",
    code:`a = True\nb = 0\nc = "False"\nd = 5 > 3`,
    options:["0 — it is falsy",'"False" — it contains False',"True and (5 > 3) — both are bool","All of the above"],
    correct:2,
    hint:"The bool type has exactly two values: True and False",
    explanation:"True is bool, 5>3 evaluates to True (also bool). 0 is int. \"False\" is str.",
    defaultRunnable:`print(type(True))    # bool\nprint(type(5 > 3))   # bool\nprint(type(0))       # int\nprint(type("False")) # str\nprint(bool(0), bool(""), bool(42), bool("hi"))`,
  },
  { id:10, topic:"Logical Operators",
    question:"What does this code print?",
    code:`x = 7\nprint(x > 5 and x < 10)\nprint(x < 0 or x > 5)\nprint(not x == 7)`,
    options:["True\nTrue\nTrue","True\nTrue\nFalse","False\nTrue\nFalse","True\nFalse\nFalse"],
    correct:1,
    hint:"Evaluate each part: x>5? x<10? Then apply and/or/not",
    explanation:"(x>5 and x<10)=True. (x<0 or x>5)=True. (not x==7)=not True=False.",
    defaultRunnable:`x = 7\nprint(x > 5 and x < 10)\nprint(x < 0 or x > 5)\nprint(not x == 7)\nfor a,b in [(True,True),(True,False),(False,False)]:\n    print(f"  {a} and {b} = {a and b}")`,
  },
  { id:11, topic:"Short-Circuit Evaluation",
    question:"What happens here when x = 0?",
    code:`x = 0\nresult = x != 0 and (10 / x > 2)\nprint(result)`,
    options:["ZeroDivisionError crash","False — right side is skipped entirely","True","None"],
    correct:1,
    hint:"With 'and', if the LEFT side is False, Python never checks the right side",
    explanation:"Short-circuit: x!=0 is False, so 10/x never runs. No crash!",
    defaultRunnable:`x = 0\nresult = x != 0 and (10 / x > 2)\nprint("and short-circuit:", result)\ny = 5\nresult2 = y == 5 or (1 / 0 > 0)\nprint("or short-circuit:", result2)`,
  },
  { id:12, topic:"if Statements",
    question:"What is printed?",
    code:`score = 85\nif score >= 90:\n    print("A")\nelif score >= 80:\n    print("B")\nelif score >= 70:\n    print("C")\nelse:\n    print("F")`,
    options:["A","B","C","B and C both print"],
    correct:1,
    hint:"Python checks top-to-bottom and runs the FIRST matching branch only",
    explanation:"score=85 fails >=90, passes >=80, so 'B' prints. All other branches are skipped.",
    defaultRunnable:`for s in [92, 85, 74, 55]:\n    if s>=90: g="A"\n    elif s>=80: g="B"\n    elif s>=70: g="C"\n    else: g="F"\n    print(f"{s} → {g}")`,
  },
  { id:13, topic:"if-else & Indentation",
    question:"What is printed when x = 3?",
    code:`x = 3\nif x > 5:\n    print("big")\n    print("number")\nprint("done")`,
    options:["big\nnumber\ndone","done","big\ndone","Nothing at all"],
    correct:1,
    hint:"Only the indented lines belong to the if block",
    explanation:'x=3 is not >5, so the indented block is skipped. print("done") is NOT indented, so it always runs.',
    defaultRunnable:`x = 3\nif x > 5:\n    print("big")\n    print("number")\nprint("done")\n# Try x = 10 to see both branches`,
  },
  { id:14, topic:"Condition vs Count-Controlled",
    question:"Which correctly distinguishes for vs while loops?",
    code:`# Count-controlled:\nfor i in range(5):\n    print(i)\n\n# Condition-controlled:\nx = 0\nwhile x < 5:\n    print(x)\n    x += 1`,
    options:["for loops are always faster","for loops run a known number of times; while runs until a condition is False","while loops are count-controlled; for is condition-controlled","They always produce identical results"],
    correct:1,
    hint:"for = you know the count in advance; while = you don't",
    explanation:"A for loop iterates a fixed number of times. A while loop runs until its condition is False.",
    defaultRunnable:`import random\nprint("FOR — count-controlled:")\nfor i in range(5): print(i, end=" ")\nprint("\nWHILE — condition-controlled:")\nc=0\nwhile random.randint(1,6)!=6: c+=1\nprint(f"Rolled {c} times before a 6")`,
  },
  { id:15, topic:"range() Function",
    question:"What does range(0, 9, 3) produce?",
    code:`for n in range(0, 9, 3):\n    print(n, end=" ")`,
    options:["0 3 6 9","0 3 6","3 6 9","0 3 6 9 12"],
    correct:1,
    hint:"range(start, stop, step) — the stop value is never included",
    explanation:"Starts at 0, steps by 3, stops BEFORE 9. Values: 0, 3, 6.",
    defaultRunnable:`for n in range(0,9,3): print(n,end=" ")\nprint()\nfor n in range(10,0,-1): print(n,end=" ")\nprint()\nfor n in range(5): print(n,end=" ")`,
  },
  { id:16, topic:"Augmented Assignment",
    question:"What is x after this code?",
    code:`x = 10\nx += 5\nx *= 2\nx -= 8\nprint(x)`,
    options:["16","22","24","30"],
    correct:1,
    hint:"Trace through: start at 10, apply each operator in order",
    explanation:"x=10 → +=5 → 15 → *=2 → 30 → -=8 → 22.",
    fillBlankAnswer:"22",
    defaultRunnable:`x = 10\nprint(f"Start:  {x}")\nx += 5;  print(f"+= 5:   {x}")\nx *= 2;  print(f"*= 2:   {x}")\nx -= 8;  print(f"-= 8:   {x}")`,
  },
  { id:17, topic:"Accumulator Pattern",
    question:"What does this loop print at the end?",
    code:`total = 0\nfor i in range(1, 6):\n    total += i\nprint(total)`,
    options:["5","14","15","6"],
    correct:2,
    hint:"Add each number: 0 + 1 + 2 + 3 + 4 + 5 = ?",
    explanation:"An accumulator starts at 0 and collects a running sum. 1+2+3+4+5 = 15.",
    fillBlankAnswer:"15",
    defaultRunnable:`total = 0\nfor i in range(1,6):\n    total += i\n    print(f"  +{i} → total={total}")\nprint(f"Final: {total}")`,
  },
  { id:18, topic:"Input Validation",
    question:"What is the purpose of input validation?",
    code:`grade = int(input("Enter grade (0-100): "))\nwhile grade < 0 or grade > 100:\n    print("Invalid!")\n    grade = int(input("Enter grade (0-100): "))\nprint("Accepted:", grade)`,
    options:["To format numbers to 2 decimal places","To check if the user typed fast enough","To keep asking until the user provides valid data","To convert strings to integers automatically"],
    correct:2,
    hint:"The loop keeps running while the condition is True — i.e., while the input is bad",
    explanation:"Input validation uses a loop to reject bad input and keep asking until valid data is provided.",
    defaultRunnable:`def get_valid(val):\n    grade = val\n    while grade < 0 or grade > 100:\n        print(f"  {grade} is invalid...")\n        grade += 50\n    return grade\nprint("Accepted:", get_valid(-10))`,
  },
  { id:19, topic:"while Loops",
    question:"How many times does the loop body execute?",
    code:`n = 1\nwhile n < 100:\n    n *= 3\nprint(n)`,
    options:["4 times, prints 81","5 times, prints 243","3 times, prints 27","Infinite loop"],
    correct:1,
    hint:"Trace through: 1 → 3 → 9 → 27 → 81 → 243. When does n ≥ 100?",
    explanation:"n: 1→3→9→27→81→243. After n=81, 81<100 so body runs again making n=243. 5 times total.",
    fillBlankAnswer:"243",
    defaultRunnable:`n=1; count=0\nwhile n<100:\n    n*=3; count+=1\n    print(f"  Iteration {count}: n={n}")\nprint(f"Ran {count} times, n={n}")`,
  },
  { id:20, topic:"Lists",
    question:"What is printed?",
    code:`items = ["a", "b", "c", "d"]\nitems[2] = "Z"\nprint(items[-1], items[2])`,
    options:["Z d","d Z","c Z","Z c"],
    correct:1,
    hint:"items[-1] is the last element. Count from the end.",
    explanation:'items[2] changes to "Z". items[-1] is the last element = "d" (unchanged). Prints: d Z.',
    defaultRunnable:`items = ["a","b","c","d"]\nitems[2] = "Z"\nprint(items[-1], items[2])\nitems.append("e")\nprint("After append:", items)\nprint("Length:", len(items))`,
  },
  { id:21, topic:"for Loops & Lists",
    question:"What is printed?",
    code:`nums = [2, 4, 6, 8]\ntotal = 0\nfor n in nums:\n    total += n\nprint(total)`,
    options:["8","20","4","2468"],
    correct:1,
    hint:"Add each element: 2 + 4 + 6 + 8 = ?",
    explanation:"The for loop iterates through each item, accumulating the total. 2+4+6+8 = 20.",
    defaultRunnable:`nums = [2,4,6,8]\ntotal = 0\nfor n in nums:\n    total += n\n    print(f"  +{n} → total={total}")\nprint(f"Sum: {total}")\nprint("Built-in:", sum(nums))`,
  },
  { id:22, topic:"void vs value-returning",
    question:"What is the key difference?",
    code:`def show(name):\n    print("Hi, " + name)\n\ndef make(name):\n    return "Hi, " + name\n\nx = show("Lee")\ny = make("Lee")`,
    options:["No difference — same result","show() prints (void, returns None); make() returns a value","make() is invalid without print()","show() is slower"],
    correct:1,
    hint:"Void functions perform an action but return None",
    explanation:"Void functions print/act and return None. Value-returning functions use return. x=show()→None. y=make()→the string.",
    defaultRunnable:`def show(name):\n    print("Hi, " + name)\ndef make(name):\n    return "Hi, " + name\nx = show("Lee")\nprint("x =", x)\ny = make("Lee")\nprint("y =", y)`,
  },
  { id:23, topic:"Functions — Define & Call",
    question:"What is printed?",
    code:`def double(n):\n    return n * 2\n\ndef add_one(n):\n    return n + 1\n\nprint(add_one(double(3)))`,
    options:["7","8","6","Error"],
    correct:0,
    hint:"Evaluate the innermost call first: what does double(3) return?",
    explanation:"double(3)=6, then add_one(6)=7.",
    fillBlankAnswer:"7",
    defaultRunnable:`def double(n): return n*2\ndef add_one(n): return n+1\nprint(add_one(double(3)))\nprint(add_one(add_one(double(5))))`,
  },
  { id:24, topic:"Local vs Global Variables",
    question:"What is printed?",
    code:`count = 0\n\ndef increment():\n    count = 10\n    print("inside:", count)\n\nincrement()\nprint("outside:", count)`,
    options:["inside: 10\noutside: 10","inside: 10\noutside: 0","inside: 0\noutside: 0","NameError"],
    correct:1,
    hint:"count = 10 inside the function creates a separate local variable",
    explanation:"Inside increment(), count=10 creates a LOCAL variable. The global count (0) is unaffected.",
    defaultRunnable:`count = 0\ndef increment():\n    count = 10\n    print("inside:", count)\ndef really_increment():\n    global count\n    count += 1\nincrement()\nprint("after increment():", count)\nreally_increment()\nprint("after really_increment():", count)`,
  },
  { id:25, topic:"Walrus Operator",
    question:"What does the walrus operator (:=) do?",
    code:`import random\n\n# Without walrus — repetitive:\nn = random.randint(1, 10)\nwhile n != 7:\n    n = random.randint(1, 10)\n\n# With walrus — concise:\nwhile (n := random.randint(1, 10)) != 7:\n    print(n)`,
    options:["Compares values like ==","Assigns a value AND returns it in one expression","Creates a deep copy","Divides and assigns like /="],
    correct:1,
    hint:":= assigns AND returns a value in the same expression",
    explanation:"The walrus operator := assigns a value AND returns it. Most useful in while loops to avoid writing the same call twice.",
    defaultRunnable:`import random\nrandom.seed(42)\nprint("Rolling until >= 8:")\nwhile (roll := random.randint(1,10)) < 8:\n    print(f"  Got {roll}...")\nprint(f"  Got {roll} — done!")`,
  },
];
