export const ALL_QUESTIONS = [
  { id:1, topic:"Syntax Errors",
    question:"Which of the following would cause a syntax error?",
    code:`# Which line has a syntax error?\nA: print("Hello")\nB: x = 5 + 3\nC: if x = 5:\nD: y = int("10")`,
    options:['print("Hello")', "x = 5 + 3", "if x = 5:", 'y = int("10")'],
    correct:2,
    hint:"Think about what = does in Python vs ==",
    explanation:'if x = 5: is a syntax error because = is assignment, not comparison. Use == to compare.',
    defaultRunnable:`x = 5\nif x == 5:\n    print("Correct operator!")\n# if x = 5:  ← SyntaxError`,
  },
  { id:2, topic:"Pseudocode & Algorithms",
    question:"What best describes pseudocode?",
    code:`# PSEUDOCODE (planning):\n# GET user's age\n# IF age >= 18 THEN\n#     PRINT "Adult"\n# ELSE\n#     PRINT "Minor"\n\n# REAL PYTHON:\nage = 20\nif age >= 18:\n    print("Adult")`,
    options:["A programming language used before Python","Informal steps describing an algorithm in plain language","Python code with lots of comments","A type of flowchart diagram"],
    correct:1,
    hint:'The word "pseudo" means fake or informal',
    explanation:"Pseudocode is informal, readable language used to plan an algorithm before writing real code. No strict syntax — the goal is clarity of logic.",
    defaultRunnable:`# Pseudocode → Python:\n# GET two numbers, PRINT the larger\na, b = 8, 3\nif a > b: print(a, "is larger")\nelif b > a: print(b, "is larger")\nelse: print("Equal")`,
  },
  { id:3, topic:"Escape Characters",
    question:'What does print("Line1\\nLine2\\tEnd") output?',
    code:`print("Line1\\nLine2\\tEnd")`,
    options:['Prints literally: Line1\\nLine2\\tEnd',"Line1, newline, Line2, tab, then End","Line1Line2End on one line","SyntaxError"],
    correct:1,
    hint:"The backslash \\ creates special invisible characters",
    explanation:"\\n is a newline and \\t is a tab. These escape sequences represent characters that can't be typed directly.",
    defaultRunnable:`print("Line1\\nLine2\\tEnd")\nprint("She said \\"hello\\"")\nprint("A\\nB\\nC")\nprint("Col1\\tCol2\\tCol3")`,
  },
  { id:4, topic:"print() end Argument",
    question:"What is the output?",
    code:`print("Hello", end=" ")\nprint("World", end="!")\nprint()`,
    options:["Hello\\nWorld!\\n","Hello World!","Hello\\nWorld!","HelloWorld!"],
    correct:1,
    hint:"The end parameter replaces the default newline at the end of print()",
    explanation:'By default print() ends with \\n. end=" " replaces that with a space. The final print() just outputs a newline.',
    defaultRunnable:`print("Hello", end=" ")\nprint("World", end="!")\nprint()\nfor i in range(5):\n    print(i, end=", ")`,
  },
  { id:5, topic:"int() Function",
    question:"What does int(3.99) return?",
    code:`print(int(3.99))\nprint(int(-3.9))\nprint(int("42"))`,
    options:["4 (rounds up)","3 (truncates toward zero)","-4","Error"],
    correct:1,
    hint:"int() chops the decimal off — it does NOT round",
    explanation:"int() truncates toward zero. int(3.99)→3. int(-3.9)→-3 (not -4). Use round() for rounding.",
    defaultRunnable:`print(int(3.99))   # 3\nprint(int(-3.9))  # -3\nprint(round(3.99)) # 4\nprint(int("42"))   # 42`,
  },
  { id:6, topic:"Math Expressions",
    question:"What is the result of this expression?",
    code:`result = 10 + 2 ** 3 * 2 - 6 / 3\nprint(result)`,
    options:["24.0","22.0","18.0","20.0"],
    correct:0,
    hint:"Use PEMDAS: ** first, then * and /, then + and -",
    explanation:"2**3=8, 8*2=16, 6/3=2.0, 10+16=26, 26-2.0=24.0. Division always returns a float.",
    fillBlankAnswer:"24.0",
    defaultRunnable:`result = 10 + 2 ** 3 * 2 - 6 / 3\nprint(result)\nstep1 = 2 ** 3\nstep2 = step1 * 2\nstep3 = 6 / 3\nstep4 = 10 + step2 - step3\nprint(step4)`,
  },
  { id:7, topic:"User Input",
    question:"A user types 98.6. Which line correctly stores it as a number?",
    code:`# User types: 98.6\nA: x = input("Temp: ")\nB: x = int(input("Temp: "))\nC: x = float(input("Temp: "))\nD: x = str(input("Temp: "))`,
    options:['input() — stores as string "98.6"',"int(input()) — crashes on 98.6","float(input()) — stores as 98.6 ✓","str(input()) — same as no conversion"],
    correct:2,
    hint:"input() always returns a string, no matter what the user types",
    explanation:"input() always returns a string. float() converts it to a float. int() would crash on '98.6'.",
    defaultRunnable:`raw = "98.6"\nprint(type(raw), raw)\nprint(type(float(raw)), float(raw))\nprint(type(int(float(raw))), int(float(raw)))`,
  },
  { id:8, topic:"Formatting Floats",
    question:"What does this f-string print?",
    code:`pi = 3.14159\nprint(f"Pi is {pi:.2f} and {pi:.4f}")`,
    options:["Pi is 3.14159 and 3.14159","Pi is 3.14 and 3.1416","Pi is 3 and 3.14","SyntaxError — invalid format"],
    correct:1,
    hint:":.2f means: format as float with 2 decimal places",
    explanation:":.2f formats with 2 decimal places. :.4f uses 4 — and rounds: 3.14159 → 3.1416.",
    defaultRunnable:`pi = 3.14159265\nprint(f"2dp: {pi:.2f}")\nprint(f"4dp: {pi:.4f}")\nprice = 4.5\nprint(f"Price: \${price:.2f}")\nbig = 1234567.89\nprint(f"Big: {big:,.2f}")`,
  },
  { id:9, topic:"Boolean Type",
    question:"Which of these is an actual bool type?",
    code:`a = True\nb = 0\nc = "False"\nd = 5 > 3`,
    options:["0 — it is falsy",'"False" — it contains False',"True and (5 > 3) — both are bool","All of the above"],
    correct:2,
    hint:"The bool type has exactly two values: True and False",
    explanation:"True is bool, 5>3 evaluates to True (also bool). 0 is int. \"False\" is str.",
    defaultRunnable:`print(type(True))    # bool\nprint(type(5 > 3))   # bool\nprint(type(0))       # int\nprint(type("False")) # str\nprint(bool(0), bool(""), bool(42), bool("hi"))`,
  },
  { id:10, topic:"Logical Operators",
    question:"What does this code print?",
    code:`x = 7\nprint(x > 5 and x < 10)\nprint(x < 0 or x > 5)\nprint(not x == 7)`,
    options:["True\nTrue\nTrue","True\nTrue\nFalse","False\nTrue\nFalse","True\nFalse\nFalse"],
    correct:1,
    hint:"Evaluate each part: x>5? x<10? Then apply and/or/not",
    explanation:"(x>5 and x<10)=True. (x<0 or x>5)=True. (not x==7)=not True=False.",
    defaultRunnable:`x = 7\nprint(x > 5 and x < 10)\nprint(x < 0 or x > 5)\nprint(not x == 7)\nfor a,b in [(True,True),(True,False),(False,False)]:\n    print(f"  {a} and {b} = {a and b}")`,
  },
  { id:11, topic:"Short-Circuit Evaluation",
    question:"What happens here when x = 0?",
    code:`x = 0\nresult = x != 0 and (10 / x > 2)\nprint(result)`,
    options:["ZeroDivisionError crash","False — right side is skipped entirely","True","None"],
    correct:1,
    hint:"With 'and', if the LEFT side is False, Python never checks the right side",
    explanation:"Short-circuit: x!=0 is False, so 10/x never runs. No crash!",
    defaultRunnable:`x = 0\nresult = x != 0 and (10 / x > 2)\nprint("and short-circuit:", result)\ny = 5\nresult2 = y == 5 or (1 / 0 > 0)\nprint("or short-circuit:", result2)`,
  },
  { id:12, topic:"if Statements",
    question:"What is printed?",
    code:`score = 85\nif score >= 90:\n    print("A")\nelif score >= 80:\n    print("B")\nelif score >= 70:\n    print("C")\nelse:\n    print("F")`,
    options:["A","B","C","B and C both print"],
    correct:1,
    hint:"Python checks top-to-bottom and runs the FIRST matching branch only",
    explanation:"score=85 fails >=90, passes >=80, so 'B' prints. All other branches are skipped.",
    defaultRunnable:`for s in [92, 85, 74, 55]:\n    if s>=90: g="A"\n    elif s>=80: g="B"\n    elif s>=70: g="C"\n    else: g="F"\n    print(f"{s} → {g}")`,
  },
  { id:13, topic:"if-else & Indentation",
    question:"What is printed when x = 3?",
    code:`x = 3\nif x > 5:\n    print("big")\n    print("number")\nprint("done")`,
    options:["big\nnumber\ndone","done","big\ndone","Nothing at all"],
    correct:1,
    hint:"Only the indented lines belong to the if block",
    explanation:'x=3 is not >5, so the indented block is skipped. print("done") is NOT indented, so it always runs.',
    defaultRunnable:`x = 3\nif x > 5:\n    print("big")\n    print("number")\nprint("done")\n# Try x = 10 to see both branches`,
  },
  { id:14, topic:"Condition vs Count-Controlled",
    question:"Which correctly distinguishes for vs while loops?",
    code:`# Count-controlled:\nfor i in range(5):\n    print(i)\n\n# Condition-controlled:\nx = 0\nwhile x < 5:\n    print(x)\n    x += 1`,
    options:["for loops are always faster","for loops run a known number of times; while runs until a condition is False","while loops are count-controlled; for is condition-controlled","They always produce identical results"],
    correct:1,
    hint:"for = you know the count in advance; while = you don't",
    explanation:"A for loop iterates a fixed number of times. A while loop runs until its condition is False.",
    defaultRunnable:`import random\nprint("FOR — count-controlled:")\nfor i in range(5): print(i, end=" ")\nprint("\nWHILE — condition-controlled:")\nc=0\nwhile random.randint(1,6)!=6: c+=1\nprint(f"Rolled {c} times before a 6")`,
  },
  { id:15, topic:"range() Function",
    question:"What does range(0, 9, 3) produce?",
    code:`for n in range(0, 9, 3):\n    print(n, end=" ")`,
    options:["0 3 6 9","0 3 6","3 6 9","0 3 6 9 12"],
    correct:1,
    hint:"range(start, stop, step) — the stop value is never included",
    explanation:"Starts at 0, steps by 3, stops BEFORE 9. Values: 0, 3, 6.",
    defaultRunnable:`for n in range(0,9,3): print(n,end=" ")\nprint()\nfor n in range(10,0,-1): print(n,end=" ")\nprint()\nfor n in range(5): print(n,end=" ")`,
  },
  { id:16, topic:"Augmented Assignment",
    question:"What is x after this code?",
    code:`x = 10\nx += 5\nx *= 2\nx -= 8\nprint(x)`,
    options:["16","22","24","30"],
    correct:1,
    hint:"Trace through: start at 10, apply each operator in order",
    explanation:"x=10 → +=5 → 15 → *=2 → 30 → -=8 → 22.",
    fillBlankAnswer:"22",
    defaultRunnable:`x = 10\nprint(f"Start:  {x}")\nx += 5;  print(f"+= 5:   {x}")\nx *= 2;  print(f"*= 2:   {x}")\nx -= 8;  print(f"-= 8:   {x}")`,
  },
  { id:17, topic:"Accumulator Pattern",
    question:"What does this loop print at the end?",
    code:`total = 0\nfor i in range(1, 6):\n    total += i\nprint(total)`,
    options:["5","14","15","6"],
    correct:2,
    hint:"Add each number: 0 + 1 + 2 + 3 + 4 + 5 = ?",
    explanation:"An accumulator starts at 0 and collects a running sum. 1+2+3+4+5 = 15.",
    fillBlankAnswer:"15",
    defaultRunnable:`total = 0\nfor i in range(1,6):\n    total += i\n    print(f"  +{i} → total={total}")\nprint(f"Final: {total}")`,
  },
  { id:18, topic:"Input Validation",
    question:"What is the purpose of input validation?",
    code:`grade = int(input("Enter grade (0-100): "))\nwhile grade < 0 or grade > 100:\n    print("Invalid!")\n    grade = int(input("Enter grade (0-100): "))\nprint("Accepted:", grade)`,
    options:["To format numbers to 2 decimal places","To check if the user typed fast enough","To keep asking until the user provides valid data","To convert strings to integers automatically"],
    correct:2,
    hint:"The loop keeps running while the condition is True — i.e., while the input is bad",
    explanation:"Input validation uses a loop to reject bad input and keep asking until valid data is provided.",
    defaultRunnable:`def get_valid(val):\n    grade = val\n    while grade < 0 or grade > 100:\n        print(f"  {grade} is invalid...")\n        grade += 50\n    return grade\nprint("Accepted:", get_valid(-10))`,
  },
  { id:19, topic:"while Loops",
    question:"How many times does the loop body execute?",
    code:`n = 1\nwhile n < 100:\n    n *= 3\nprint(n)`,
    options:["4 times, prints 81","5 times, prints 243","3 times, prints 27","Infinite loop"],
    correct:1,
    hint:"Trace through: 1 → 3 → 9 → 27 → 81 → 243. When does n ≥ 100?",
    explanation:"n: 1→3→9→27→81→243. After n=81, 81<100 so body runs again making n=243. 5 times total.",
    fillBlankAnswer:"243",
    defaultRunnable:`n=1; count=0\nwhile n<100:\n    n*=3; count+=1\n    print(f"  Iteration {count}: n={n}")\nprint(f"Ran {count} times, n={n}")`,
  },
  { id:20, topic:"Lists",
    question:"What is printed?",
    code:`items = ["a", "b", "c", "d"]\nitems[2] = "Z"\nprint(items[-1], items[2])`,
    options:["Z d","d Z","c Z","Z c"],
    correct:1,
    hint:"items[-1] is the last element. Count from the end.",
    explanation:'items[2] changes to "Z". items[-1] is the last element = "d" (unchanged). Prints: d Z.',
    defaultRunnable:`items = ["a","b","c","d"]\nitems[2] = "Z"\nprint(items[-1], items[2])\nitems.append("e")\nprint("After append:", items)\nprint("Length:", len(items))`,
  },
  { id:21, topic:"for Loops & Lists",
    question:"What is printed?",
    code:`nums = [2, 4, 6, 8]\ntotal = 0\nfor n in nums:\n    total += n\nprint(total)`,
    options:["8","20","4","2468"],
    correct:1,
    hint:"Add each element: 2 + 4 + 6 + 8 = ?",
    explanation:"The for loop iterates through each item, accumulating the total. 2+4+6+8 = 20.",
    defaultRunnable:`nums = [2,4,6,8]\ntotal = 0\nfor n in nums:\n    total += n\n    print(f"  +{n} → total={total}")\nprint(f"Sum: {total}")\nprint("Built-in:", sum(nums))`,
  },
  { id:22, topic:"void vs value-returning",
    question:"What is the key difference?",
    code:`def show(name):\n    print("Hi, " + name)\n\ndef make(name):\n    return "Hi, " + name\n\nx = show("Lee")\ny = make("Lee")`,
    options:["No difference — same result","show() prints (void, returns None); make() returns a value","make() is invalid without print()","show() is slower"],
    correct:1,
    hint:"Void functions perform an action but return None",
    explanation:"Void functions print/act and return None. Value-returning functions use return. x=show()→None. y=make()→the string.",
    defaultRunnable:`def show(name):\n    print("Hi, " + name)\ndef make(name):\n    return "Hi, " + name\nx = show("Lee")\nprint("x =", x)\ny = make("Lee")\nprint("y =", y)`,
  },
  { id:23, topic:"Functions — Define & Call",
    question:"What is printed?",
    code:`def double(n):\n    return n * 2\n\ndef add_one(n):\n    return n + 1\n\nprint(add_one(double(3)))`,
    options:["7","8","6","Error"],
    correct:0,
    hint:"Evaluate the innermost call first: what does double(3) return?",
    explanation:"double(3)=6, then add_one(6)=7.",
    fillBlankAnswer:"7",
    defaultRunnable:`def double(n): return n*2\ndef add_one(n): return n+1\nprint(add_one(double(3)))\nprint(add_one(add_one(double(5))))`,
  },
  { id:24, topic:"Local vs Global Variables",
    question:"What is printed?",
    code:`count = 0\n\ndef increment():\n    count = 10\n    print("inside:", count)\n\nincrement()\nprint("outside:", count)`,
    options:["inside: 10\noutside: 10","inside: 10\noutside: 0","inside: 0\noutside: 0","NameError"],
    correct:1,
    hint:"count = 10 inside the function creates a separate local variable",
    explanation:"Inside increment(), count=10 creates a LOCAL variable. The global count (0) is unaffected.",
    defaultRunnable:`count = 0\ndef increment():\n    count = 10\n    print("inside:", count)\ndef really_increment():\n    global count\n    count += 1\nincrement()\nprint("after increment():", count)\nreally_increment()\nprint("after really_increment():", count)`,
  },
  { id:25, topic:"Walrus Operator",
    question:"What does the walrus operator (:=) do?",
    code:`import random\n\n# Without walrus — repetitive:\nn = random.randint(1, 10)\nwhile n != 7:\n    n = random.randint(1, 10)\n\n# With walrus — concise:\nwhile (n := random.randint(1, 10)) != 7:\n    print(n)`,
    options:["Compares values like ==","Assigns a value AND returns it in one expression","Creates a deep copy","Divides and assigns like /="],
    correct:1,
    hint:":= assigns AND returns a value in the same expression",
    explanation:"The walrus operator := assigns a value AND returns it. Most useful in while loops to avoid writing the same call twice.",
    defaultRunnable:`import random\nrandom.seed(42)\nprint("Rolling until >= 8:")\nwhile (roll := random.randint(1,10)) < 8:\n    print(f"  Got {roll}...")\nprint(f"  Got {roll} — done!")`,
  },

  // ── Ch. 6 — Lists Deep Dive ───────────────────────────────────────────────

  { id:26, topic:"List Indexing",
    question:"What is printed?",
    code:`animals = ["cat", "dog", "bird", "fish"]\nprint(animals[0])\nprint(animals[-2])\nprint(animals[3])`,
    options:["cat, dog, fish","cat, bird, fish","dog, bird, bird","cat, bird, bird"],
    correct:1,
    hint:'Positive indexes count from the front (0 = first element). Negative indexes count from the back: -1 = last, -2 = second-to-last. The list has 4 items — which item is at -2?',
    explanation:'animals[0] is the first element → "cat". animals[-2] counts 2 from the end: the list is ["cat","dog","bird","fish"], so 2nd from the end is "bird". animals[3] is index 3 (the 4th element) → "fish". Three separate print() calls produce three lines of output: cat / bird / fish.',
    defaultRunnable:`animals = ["cat", "dog", "bird", "fish"]\nprint(animals[0])   # first\nprint(animals[-2])  # second-to-last\nprint(animals[3])   # last`,
  },
  { id:27, topic:"Lists vs Tuples",
    question:"What is the key difference between a list and a tuple?",
    code:`my_list  = [1, 2, 3]   # mutable\nmy_tuple = (1, 2, 3)   # immutable\n\nmy_list[0] = 99   # works fine\nmy_tuple[0] = 99  # TypeError!`,
    options:["Tuples can only hold numbers; lists hold anything","Lists are mutable (changeable); tuples are immutable (fixed)","Tuples are faster but otherwise identical","Lists use [] and tuples use () — that's the only difference"],
    correct:1,
    hint:"Try running my_tuple[0] = 99 — what happens? The key difference is not bracket style or content type, but whether you can change the contents after creation.",
    explanation:"Lists are mutable — you can change, add, or remove elements after creation. Tuples are immutable — once created, the contents cannot be modified; any attempt raises TypeError. Both can hold mixed types. Use tuples for fixed data (like coordinates) and lists for data that changes over time.",
    defaultRunnable:`my_list  = [1, 2, 3]\nmy_tuple = (1, 2, 3)\nmy_list[0] = 99\nprint("List:", my_list)\nprint("Tuple:", my_tuple)\n# my_tuple[0] = 99  # would raise TypeError`,
  },
  { id:28, topic:"range() to list",
    question:"How do you convert range(1, 6) into an actual list?",
    code:`# Which correctly produces [1, 2, 3, 4, 5]?\nA: range(1, 6)\nB: list(range(1, 6))\nC: [range(1, 6)]\nD: range.list(1, 6)`,
    options:["range(1, 6) — already a list","list(range(1, 6)) — wraps range in list()","[range(1, 6)] — bracket syntax","range.list(1, 6) — built-in method"],
    correct:1,
    hint:"range() returns a lazy range object that generates numbers on demand — it is NOT a list. Python's built-in list() function converts any iterable into a proper list. Think: list(...).",
    explanation:"range() returns a range object, not a list. To convert: list(range(1, 6)) → [1, 2, 3, 4, 5]. Option A fails because range alone is still a range object. Option C puts the range object inside a list as a single item: [range(0, 6)] — not the same thing. Option D doesn't exist in Python.",
    defaultRunnable:`r = range(1, 6)\nprint(type(r), r)\nresult = list(r)\nprint(type(result), result)\nprint(list(range(0, 10, 2)))`,
  },
  { id:29, topic:"List/Tuple Conversion",
    question:"What does this code print?",
    code:`data = (10, 20, 30)\nas_list = list(data)\nas_list.append(40)\nback = tuple(as_list)\nprint(back)`,
    options:["(10, 20, 30)","[10, 20, 30, 40]","(10, 20, 30, 40)","TypeError"],
    correct:2,
    hint:"Trace each step: list() converts the tuple to a mutable list so you can append. Then tuple() converts back. What does the final tuple look like, and which brackets does Python use when printing a tuple?",
    explanation:"Step by step: data = (10, 20, 30). list(data) → [10, 20, 30] (now a mutable list). .append(40) → [10, 20, 30, 40]. tuple([10, 20, 30, 40]) → (10, 20, 30, 40). Python prints tuples with round brackets (). Option B shows square brackets — that would be a list, not a tuple.",
    defaultRunnable:`data = (10, 20, 30)\nas_list = list(data)\nas_list.append(40)\nback = tuple(as_list)\nprint(back)\nprint(type(back))`,
  },
  { id:30, topic:"List Repetition",
    question:"What does the * operator do with lists?",
    code:`a = [0] * 4\nb = [1, 2] * 3\nprint(a)\nprint(b)`,
    options:["Error — * only works with numbers","[0, 0, 0, 0] and [1, 2, 1, 2, 1, 2]","[0, 4] and [1, 2, 3]","[[0]*4] and [[1,2]*3]"],
    correct:1,
    hint:"[0] * 4 repeats the list [0] four times end-to-end — it is NOT multiplying the number 0 by 4. [1, 2] * 3 repeats the whole two-element list three times.",
    explanation:"The * operator repeats list contents n times: [0] * 4 → [0, 0, 0, 0] (the list [0] repeated 4 times, giving 4 elements). [1, 2] * 3 → [1, 2, 1, 2, 1, 2] (the list [1, 2] repeated 3 times, giving 6 elements). This is identical to string repetition: 'ab' * 3 → 'ababab'.",
    defaultRunnable:`a = [0] * 4\nb = [1, 2] * 3\nprint(a)\nprint(b)\nprint([None] * 5)`,
  },
  { id:31, topic:"List Exceptions",
    question:"Which exception is raised by this code?",
    code:`items = ["a", "b", "c"]\nprint(items[5])`,
    options:["ValueError","KeyError","IndexError","TypeError"],
    correct:2,
    hint:'The list has 3 elements with valid indices 0, 1, 2 (and negatives -1, -2, -3). Index 5 is way past the end. Python raises a specific error for out-of-range indexes — not ValueError (wrong value) or TypeError (wrong type).',
    explanation:'items has 3 elements, so valid indices are 0, 1, 2. Accessing index 5 is outside this range → IndexError: list index out of range. Cheat sheet: IndexError = bad index; ValueError = value not found (e.g., .remove("z") when "z" isn\'t in the list); TypeError = wrong type used as index (e.g., items[1.5]); KeyError = missing key in a dictionary.',
    defaultRunnable:`items = ["a", "b", "c"]\ntry:\n    print(items[5])\nexcept IndexError as e:\n    print("IndexError:", e)\ntry:\n    items.remove("z")\nexcept ValueError as e:\n    print("ValueError:", e)`,
  },
  { id:32, topic:"len() Function",
    question:"What is printed?",
    code:`words = ["hello", "world", "python"]\nprint(len(words))\nprint(len(words[0]))`,
    options:["3 and 5","3 and 3","5 and 3","2 and 5"],
    correct:0,
    hint:'Two separate print() calls produce two lines — in the order they appear. The FIRST print calls len() on the whole list (how many words?). The SECOND calls len() on words[0] = "hello" (how many characters?). The answer lists the results in that same top-to-bottom order.',
    explanation:'Line 1: len(words) = len(["hello", "world", "python"]) = 3 (three strings in the list). Line 2: len(words[0]) = len("hello") = 5 (h-e-l-l-o = 5 characters). Output: 3 on the first line, then 5 on the second line → "3 and 5". Common mistake: choosing "5 and 3" by thinking of the string length first — but the list length is printed first.',
    defaultRunnable:`words = ["hello", "world", "python"]\nprint(len(words))      # 3 elements in the list\nprint(len(words[0]))   # 5 chars in "hello"\nprint(len([]))         # 0`,
  },
  { id:33, topic:"for Loops & Strings",
    question:"What does this print?",
    code:`fruits = ["apple", "banana", "cherry"]\nfor fruit in fruits:\n    print(fruit.upper())`,
    options:["apple banana cherry on one line","APPLE, BANANA, CHERRY each on their own line","apple, banana, cherry each on their own line","Error — upper() not valid here"],
    correct:1,
    hint:"Trace the loop: fruit = 'apple' → 'apple'.upper() = 'APPLE' → printed on its own line. Then repeat for 'banana' and 'cherry'. Each call to print() produces a new line.",
    explanation:"The for loop assigns each list element to fruit in turn. .upper() converts every letter to uppercase. Each print() call ends with a newline by default, so results appear on separate lines: APPLE (line 1), BANANA (line 2), CHERRY (line 3). upper() works on any string — it's a standard string method, not restricted to print().",
    defaultRunnable:`fruits = ["apple", "banana", "cherry"]\nfor fruit in fruits:\n    print(fruit.upper())`,
  },
  { id:34, topic:"Substring Check",
    question:"Which correctly checks if a string contains a substring?",
    code:`sentence = "The quick brown fox"`,
    options:['sentence.contains("quick")','"quick" in sentence','sentence.find("quick") == True','search("quick", sentence)'],
    correct:1,
    hint:'Python uses the "in" keyword directly — no method call needed. "quick" in sentence returns True or False. sentence.contains() would be Java/JavaScript syntax; it does not exist in Python.',
    explanation:'"quick" in sentence → True. This is Python\'s membership test operator, usable with strings, lists, tuples, and more. Option A (contains) doesn\'t exist in Python — that\'s Java/JavaScript. Option C: find() returns the starting index (e.g. 4) if found, or -1 if not; comparing it to True doesn\'t give a reliable boolean. Option D: search() is from the re module and requires import re.',
    defaultRunnable:`sentence = "The quick brown fox"\nprint("quick" in sentence)\nprint("slow" in sentence)\nprint(sentence.find("quick"))  # returns index, not True/False`,
  },
  { id:35, topic:"List Concatenation",
    question:"What is printed?",
    code:`a = [1, 2, 3]\nb = [4, 5, 6]\nc = a + b\nprint(c)\nprint(len(c))`,
    options:["[1, 2, 3, 4, 5, 6] and 6","[5, 7, 9] and 3","[[1,2,3],[4,5,6]] and 2","Error — can't add lists"],
    correct:0,
    hint:"The + operator on two lists joins them end-to-end (like 'ab' + 'cd' = 'abcd' for strings). It does NOT add the numbers together elementwise — that would require a loop or zip().",
    explanation:"a + b places all of a's elements followed by all of b's elements into a new list: [1, 2, 3, 4, 5, 6]. This is concatenation, not addition. Option B ([5,7,9]) would be elementwise addition — Python lists don't do that with +. len([1,2,3,4,5,6]) = 6 because the combined list has 6 elements.",
    defaultRunnable:`a = [1, 2, 3]\nb = [4, 5, 6]\nc = a + b\nprint(c)\nprint(len(c))`,
  },

  // ── Ch. 7 — Strings ──────────────────────────────────────────────────────

  { id:36, topic:"List Slicing",
    question:"What does this print?",
    code:`nums = [10, 20, 30, 40, 50]\nprint(nums[1:4])\nprint(nums[:2])\nprint(nums[::2])`,
    options:["[20,30,40], [10,20], [10,30,50]","[20,30,40], [10,20,30], [10,30,50]","[10,20,30], [10,20], [20,40]","[20,30,40], [10], [10,30,50]"],
    correct:0,
    hint:"nums[1:4]: start at index 1, stop BEFORE index 4 (indices 1,2,3 only). nums[:2]: from start, stop before index 2 (indices 0,1). nums[::2]: step=2 means every 2nd element starting from index 0 — that picks indices 0, 2, 4.",
    explanation:"nums = [10,20,30,40,50] (indices 0–4). nums[1:4]: indices 1,2,3 → [20,30,40] (index 4 excluded — the stop is always excluded). nums[:2]: indices 0,1 → [10,20]. nums[::2]: step 2 from index 0 → indices 0,2,4 → [10,30,50]. Option B is wrong because nums[:2] gives only 2 elements, not 3.",
    defaultRunnable:`nums = [10, 20, 30, 40, 50]\nprint(nums[1:4])\nprint(nums[:2])\nprint(nums[::2])\nprint(nums[::-1])  # reversed`,
  },
  { id:37, topic:"split() and strip()",
    question:"What does this code print?",
    code:`line = "  hello world  "\nwords = line.strip().split()\nprint(words)\nprint(len(words))`,
    options:['["hello", "world"] and 2','["  hello", "world  "] and 2','["hello world"] and 1',"Error"],
    correct:0,
    hint:'Step 1: line.strip() removes the leading 2 spaces and trailing 2 spaces, giving "hello world". Step 2: .split() with NO argument splits on any whitespace and trims extras — it never leaves empty strings.',
    explanation:'strip() removes leading and trailing whitespace: "  hello world  " → "hello world". Then .split() with no argument splits on any whitespace run → ["hello", "world"]. len(["hello","world"]) = 2. Option B is wrong because strip() already removed the outer spaces. Option C is wrong because split() separates the two words.',
    defaultRunnable:`line = "  hello world  "\nprint(repr(line.strip()))\nwords = line.strip().split()\nprint(words)\nprint(len(words))\nprint("a,b,c".split(","))`,
  },
  { id:38, topic:"String Methods",
    question:"What is printed?",
    code:`s = "Hello123"\nprint(s.upper())\nprint(s.isalpha())\nprint(s.isdigit())\nprint(s.isupper())\nprint(s.endswith("23"))\nprint(s.replace("Hello", "Bye"))`,
    options:["HELLO123, True, False, False, True, Bye123","HELLO123, False, False, False, True, Bye123","HELLO123, True, True, True, True, Bye123","HELLO123, False, True, False, True, Bye123"],
    correct:1,
    hint:"isalpha() and isdigit() require ALL characters to match — even one digit makes isalpha() False, and even one letter makes isdigit() False. isupper() checks whether ALL cased letters are uppercase — 'Hello' has lowercase letters.",
    explanation:'s = "Hello123". upper() → "HELLO123". isalpha() → False (digits 1,2,3 are not letters). isdigit() → False (letters H,e,l,l,o are not digits). isupper() → False (original "Hello" has lowercase e,l,l,o — isupper requires ALL letters to be uppercase). endswith("23") → True (last two chars are 2 and 3). replace("Hello","Bye") → "Bye123".',
    defaultRunnable:`s = "Hello123"\nprint(s.upper())\nprint(s.isalpha())\nprint(s.isdigit())\nprint(s.isupper())\nprint(s.endswith("23"))\nprint(s.replace("Hello", "Bye"))`,
  },
  { id:39, topic:"String Concatenation",
    question:"What is printed?",
    code:`first = "Python"\nlast  = "Quiz"\nresult = first + " " + last + "!"\nprint(result)\nprint(len(result))`,
    options:["Python Quiz! and 12","PythonQuiz! and 11","Python Quiz and 11","Python Quiz! and 11"],
    correct:0,
    hint:'Count every character in "Python Quiz!" — including the space and the exclamation mark: P-y-t-h-o-n = 6, SPACE = 1, Q-u-i-z = 4, ! = 1. Total = 6+1+4+1 = ?',
    explanation:'"Python" + " " + "Quiz" + "!" = "Python Quiz!". Counting: P(1)y(2)t(3)h(4)o(5)n(6) (7=SPACE)Q(8)u(9)i(10)z(11)!(12) = 12 characters. Watch out for option D — it also shows "Python Quiz!" but claims len = 11, forgetting to count the space.',
    defaultRunnable:`first = "Python"\nlast  = "Quiz"\nresult = first + " " + last + "!"\nprint(result)\nprint(len(result))`,
  },
  { id:40, topic:"Functions with Strings",
    question:"What does this print?",
    code:`def shout(text):\n    return text.upper() + "!!!"\n\nmessage = shout("hello")\nprint(message)`,
    options:["hello!!!","HELLO!!!","HELLO","Error — upper() only works inside print()"],
    correct:1,
    hint:'Follow the call: shout receives text = "hello". text.upper() converts every letter to uppercase → "HELLO". Then "HELLO" + "!!!" concatenates the exclamation marks. The function returns this combined string.',
    explanation:'shout("hello"): text = "hello". text.upper() → "HELLO". "HELLO" + "!!!" → "HELLO!!!". The function returns "HELLO!!!". message = "HELLO!!!". print(message) outputs HELLO!!!. upper() is a standard string method — it works anywhere on a string, not just inside print().',
    defaultRunnable:`def shout(text):\n    return text.upper() + "!!!"\n\nprint(shout("hello"))\nprint(shout("quiet"))\nprint(shout("python"))`,
  },

  // ── Ch. 8 — OOP ──────────────────────────────────────────────────────────

  { id:41, topic:"Object-Oriented Programming",
    question:"Which best describes object-oriented programming?",
    code:`class Dog:\n    def __init__(self, name):\n        self.name = name\n    def bark(self):\n        print(f"{self.name} says: Woof!")`,
    options:["Writing code with lots of functions","A style that organizes code into classes that bundle data and behavior together","Using only loops and conditions","Programming without variables"],
    correct:1,
    hint:"OOP is a programming paradigm (a style of organising code). Think about what a class contains: both data (what the object knows — attributes) and behaviour (what it can do — methods). This models real-world things.",
    explanation:"OOP organises code into classes that bundle together data (attributes, e.g. self.name) and behaviour (methods, e.g. bark()). A Dog class models a dog — it knows its name and can bark. Contrast with procedural programming, which is just a sequence of functions with separate data. OOP makes large programs easier to understand, reuse, and maintain.",
    defaultRunnable:`class Dog:\n    def __init__(self, name):\n        self.name = name\n    def bark(self):\n        print(f"{self.name} says: Woof!")\nfido = Dog("Fido")\nfido.bark()`,
  },
  { id:42, topic:"Classes and Objects",
    question:"What is the relationship between a class and an object?",
    code:`class Dog:\n    def __init__(self, name):\n        self.name = name\n\nfido  = Dog("Fido")\nbuddy = Dog("Buddy")`,
    options:["A class is an instance; an object is the blueprint","A class is the blueprint; an object is an instance created from it","They are the same thing with different names","An object holds classes inside it"],
    correct:1,
    hint:"The class is the cookie cutter — it defines the shape. An object is an actual cookie made using that cutter. Dog is defined once; fido and buddy are two separate real dogs created from it.",
    explanation:"A class is the blueprint or template — it defines what attributes and methods all instances will have. An object (instance) is a specific thing created from that blueprint. Dog is the class (written once). Dog('Fido') creates one object; Dog('Buddy') creates another. Both are Dogs with a .name attribute, but they are completely independent objects with different names.",
    defaultRunnable:`class Dog:\n    def __init__(self, name):\n        self.name = name\n\nfido  = Dog("Fido")\nbuddy = Dog("Buddy")\nprint(fido.name)\nprint(buddy.name)\nprint(type(fido))`,
  },
  { id:43, topic:"Defining a Class",
    question:"Which correctly defines a class with one attribute?",
    code:`# Correct:\nclass Car:\n    def __init__(self, color):\n        self.color = color`,
    options:["class Car() with a class-level variable","class Car: with __init__ and self.color","def class Car: — hybrid syntax","Car = class { color: 'red' } — JavaScript syntax"],
    correct:1,
    hint:"A Python class header is 'class ClassName:' with a colon (parentheses are only needed when inheriting). Instance attributes are set inside __init__ using self.attribute_name = value.",
    explanation:"class Car: is the correct header — no parentheses needed unless inheriting. The __init__ method receives self (the new object being created) plus parameters. self.color = color stores color as an attribute on that specific instance. Option A: class-level variables are shared by all instances (a different concept). Option C: def class is invalid Python syntax. Option D: that's JavaScript object literal syntax.",
    defaultRunnable:`class Car:\n    def __init__(self, color):\n        self.color = color\n\nmy_car = Car("red")\nprint(my_car.color)`,
  },
  { id:44, topic:"Encapsulation",
    question:"What does encapsulation mean in OOP?",
    code:`class BankAccount:\n    def __init__(self, balance):\n        self.__balance = balance  # private!\n\n    def get_balance(self):\n        return self.__balance`,
    options:["Hiding data inside an object and controlling access through methods","Making all variables global","Copying one class into another","Running code faster by grouping it"],
    correct:0,
    hint:"Encapsulation is about two things: (1) bundling data together with the methods that manage it, and (2) hiding internal details from the outside. The __ prefix makes __balance private — external code can't access it directly.",
    explanation:"Encapsulation means: (1) bundle data and methods together in a class, and (2) restrict direct access to internal data. __balance uses name-mangling (becomes _BankAccount__balance) to prevent direct external access. Code outside the class must go through get_balance() instead. This prevents accidental corruption, allows validation in setters, and lets you change the internal implementation without breaking code that uses the class.",
    defaultRunnable:`class BankAccount:\n    def __init__(self, balance):\n        self.__balance = balance\n    def get_balance(self):\n        return self.__balance\n\nacc = BankAccount(100)\nprint(acc.get_balance())`,
  },
  { id:45, topic:"Getters and Setters",
    question:"What are getters and setters?",
    code:`class Temperature:\n    def get_celsius(self):      # getter / accessor\n        return self.__celsius\n\n    def set_celsius(self, val): # setter / mutator\n        if val >= -273.15:\n            self.__celsius = val`,
    options:["get() and set() for dictionaries","Methods that read (getter) or modify (setter) private attributes safely","Built-in Python functions for list operations","The __init__ and __str__ methods"],
    correct:1,
    hint:"Getter = accessor = 'get me the current value of the private attribute'. Setter = mutator = 'set this attribute to a new value, with validation'. Together they enforce encapsulation by controlling how private data is read and changed.",
    explanation:"A getter (accessor) reads and returns a private attribute: get_celsius() returns self.__celsius. A setter (mutator) changes a private attribute, often with validation first: set_celsius() checks val >= -273.15 (absolute zero) before accepting it. Without setters, external code could set __celsius to -9999, which is physically impossible. Getters and setters are how encapsulation works in practice.",
    defaultRunnable:`class Temperature:\n    def __init__(self, c):\n        self.__celsius = c\n    def get_celsius(self):\n        return self.__celsius\n    def set_celsius(self, val):\n        if val >= -273.15:\n            self.__celsius = val\nt = Temperature(20)\nprint(t.get_celsius())\nt.set_celsius(25)\nprint(t.get_celsius())`,
  },
  { id:46, topic:"__init__ Method",
    question:"What is the purpose of __init__?",
    code:`class Person:\n    def __init__(self, name, age):\n        self.name = name\n        self.age  = age\n\np = Person("Alice", 30)`,
    options:["It imports the class from another file","It runs automatically when an object is created, setting up its initial attributes","It destroys the object when done","It makes the class printable"],
    correct:1,
    hint:"__init__ stands for 'initialise'. It's Python's constructor method. The instant you write Person('Alice', 30), Python creates a blank Person object and immediately calls __init__(self, 'Alice', 30) to set it up.",
    explanation:"__init__ is the constructor — it runs automatically the moment you create an instance. Person('Alice', 30): Python creates a new Person object, then calls __init__(self, 'Alice', 30). self refers to the new object. self.name = 'Alice' and self.age = 30 store the values as attributes. After __init__ finishes, p.name gives 'Alice' and p.age gives 30. The double underscores (__) mean it's a 'dunder' (magic) method with special Python behaviour.",
    defaultRunnable:`class Person:\n    def __init__(self, name, age):\n        self.name = name\n        self.age  = age\n\np = Person("Alice", 30)\nprint(p.name, p.age)`,
  },
  { id:47, topic:"__str__ Method",
    question:"What does __str__ do?",
    code:`class Point:\n    def __init__(self, x, y):\n        self.x = x\n        self.y = y\n\n    def __str__(self):\n        return f"Point({self.x}, {self.y})"\n\np = Point(3, 7)\nprint(p)  # → Point(3, 7)`,
    options:["It converts the object to an integer","It defines what print(object) displays — a human-readable string","It stores the object as a string internally","It renames the class"],
    correct:1,
    hint:"When Python encounters print(p), it needs to turn p into a string for display. It calls p.__str__() to do this. Without __str__, Python shows a useless memory address like <__main__.Point object at 0x10fa3b2e0>.",
    explanation:"__str__ defines the human-readable string representation of an object. When you print(p), Python internally calls str(p) which calls p.__str__(). The method returns f'Point({self.x}, {self.y})' → 'Point(3, 7)', which is then displayed. Without __str__, you'd see something like <__main__.Point object at 0x10fa3b2e0>. You can also use it directly: str(p) → 'Point(3, 7)'.",
    defaultRunnable:`class Point:\n    def __init__(self, x, y):\n        self.x = x\n        self.y = y\n    def __str__(self):\n        return f"Point({self.x}, {self.y})"\n\np = Point(3, 7)\nprint(p)`,
  },
  { id:48, topic:"Objects as Arguments",
    question:"What is printed?",
    code:`class Circle:\n    def __init__(self, radius):\n        self.radius = radius\n\ndef area(shape):\n    return 3.14 * shape.radius ** 2\n\nc = Circle(5)\nprint(area(c))`,
    options:["Error — objects can't be passed to functions","25.0 (radius squared only)","78.5","3.14"],
    correct:2,
    hint:"Objects are passed to functions exactly like any other value. Inside area(), the parameter shape IS the Circle object c. You can access its attributes with shape.radius. Calculate: 3.14 × (5²) = 3.14 × 25 = ?",
    explanation:"Python passes objects to functions by reference — no special syntax needed. Inside area(shape), shape is the Circle c, so shape.radius = 5. Calculation: 3.14 × (5²) = 3.14 × 25 = 78.5. Option B (25.0) would be just radius² without multiplying by 3.14. Python doesn't restrict what types a function parameter can accept — as long as the object has a .radius attribute, it works.",
    defaultRunnable:`class Circle:\n    def __init__(self, radius):\n        self.radius = radius\n\ndef area(shape):\n    return 3.14 * shape.radius ** 2\n\nc = Circle(5)\nprint(area(c))`,
  },
  { id:49, topic:"Polymorphism",
    question:"What does polymorphism mean in OOP?",
    code:`class Dog:\n    def speak(self):\n        return "Woof!"\n\nclass Cat:\n    def speak(self):\n        return "Meow!"\n\ndef make_sound(animal):\n    print(animal.speak())\n\nmake_sound(Dog())  # Woof!\nmake_sound(Cat())  # Meow!`,
    options:["All classes must have the same methods","A class can inherit from multiple parents","Different objects can respond to the same method call in their own way","A function can only accept one type of argument"],
    correct:2,
    hint:'"Poly" = many, "morph" = form. The same method call (animal.speak()) produces different output depending on the TYPE of object passed in. Dog and Cat both have speak(), but they do different things.',
    explanation:'Polymorphism means "many forms." The same operation (speak()) produces different results based on the actual type of the object. make_sound(Dog()) → animal.speak() calls Dog\'s speak → "Woof!". make_sound(Cat()) → animal.speak() calls Cat\'s speak → "Meow!". The make_sound function doesn\'t need to know which type it received — it just calls speak() and polymorphism handles the rest. This lets you write flexible, extensible code.',
    defaultRunnable:`class Dog:\n    def speak(self):\n        return "Woof!"\nclass Cat:\n    def speak(self):\n        return "Meow!"\n\nfor animal in [Dog(), Cat(), Dog()]:\n    print(animal.speak())`,
  },
  { id:50, topic:"Inheritance",
    question:"What does inheritance allow?",
    code:`class Animal:\n    def __init__(self, name):\n        self.name = name\n    def eat(self):\n        print(f"{self.name} is eating")\n\nclass Dog(Animal):        # Dog inherits from Animal\n    def bark(self):\n        print("Woof!")\n\nd = Dog("Rex")\nd.eat()   # inherited from Animal\nd.bark()  # defined in Dog`,
    options:["Copying code from one file to another","A class to acquire the attributes and methods of another class","Making two classes identical","Running a function automatically"],
    correct:1,
    hint:"class Dog(Animal) means Dog inherits from Animal. Dog automatically gets ALL of Animal's attributes and methods for free. Dog only defines what's new or different — in this case, just bark().",
    explanation:"Inheritance lets a child class (Dog) automatically acquire all attributes and methods from a parent class (Animal). Dog defines only bark() — but it also inherits __init__(self, name) and eat() from Animal without copy-pasting them. d = Dog('Rex') calls Animal's __init__ (since Dog has none of its own). d.eat() works because Dog inherits eat(). d.bark() works because Dog defines it. Inheritance promotes code reuse and creates an 'is-a' relationship: a Dog IS-A Animal.",
    defaultRunnable:`class Animal:\n    def __init__(self, name):\n        self.name = name\n    def eat(self):\n        print(f"{self.name} is eating")\n\nclass Dog(Animal):\n    def bark(self):\n        print("Woof!")\n\nd = Dog("Rex")\nd.eat()\nd.bark()`,
  },
  { id:51, topic:"Base Class vs Subclass",
    question:"In class Dog(Animal):, what are Dog and Animal?",
    code:`class Animal:        # base class (parent / superclass)\n    def breathe(self):\n        print("breathing")\n\nclass Dog(Animal):   # subclass (child / derived class)\n    def bark(self):\n        print("woof")`,
    options:["Animal is the subclass; Dog is the base class","They are both base classes","Animal is the base class (parent); Dog is the subclass (child)","Dog and Animal are both subclasses of Python's object class only"],
    correct:2,
    hint:"In 'class Dog(Animal)', read it as 'Dog inherits FROM Animal'. The class listed in parentheses is the parent/base class — the one being inherited from. The class being defined (Dog) is the child/subclass.",
    explanation:"The base class (parent/superclass) is the class being inherited FROM — Animal. It provides base functionality. The subclass (child/derived class) is the class that inherits — Dog. It extends or overrides the base class. Key terms: Animal = base class = parent class = superclass. Dog = subclass = child class = derived class. isinstance(d, Animal) returns True because Dog inherits from Animal — every Dog IS-A Animal.",
    defaultRunnable:`class Animal:\n    def breathe(self):\n        print("breathing")\n\nclass Dog(Animal):\n    def bark(self):\n        print("woof")\n\nd = Dog()\nd.breathe()  # from Animal\nd.bark()     # from Dog\nprint(isinstance(d, Animal))  # True`,
  },
];
